/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the LineItemJurisTax type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LineItemJurisTax{}

// LineItemJurisTax Taxes for a line item for a jurisdiction or region.
type LineItemJurisTax struct {
	// The ID of the jurisdiction or region.
	Id *string `json:"id,omitempty"`
	// The name of the jurisdiction or region.
	Name *string `json:"name,omitempty"`
	// The non-taxable amount of the line item in the smallest denomination of the currency (e.g. cents or pennies).
	NonTaxableAmount *string `json:"nonTaxableAmount,omitempty"`
	Exemptions []LineItemJurisTaxExemptionsInner `json:"exemptions,omitempty"`
	// The taxable amount of the line item in the smallest denomination of the currency (e.g. cents or pennies).
	TaxableAmount *string `json:"taxableAmount,omitempty"`
	// The tax rate.
	Rate NullableString `json:"rate,omitempty"`
	TaxAmount *LineItemJurisTaxTaxAmount `json:"taxAmount,omitempty"`
}

// NewLineItemJurisTax instantiates a new LineItemJurisTax object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLineItemJurisTax() *LineItemJurisTax {
	this := LineItemJurisTax{}
	return &this
}

// NewLineItemJurisTaxWithDefaults instantiates a new LineItemJurisTax object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLineItemJurisTaxWithDefaults() *LineItemJurisTax {
	this := LineItemJurisTax{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *LineItemJurisTax) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LineItemJurisTax) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *LineItemJurisTax) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *LineItemJurisTax) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *LineItemJurisTax) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LineItemJurisTax) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *LineItemJurisTax) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *LineItemJurisTax) SetName(v string) {
	o.Name = &v
}

// GetNonTaxableAmount returns the NonTaxableAmount field value if set, zero value otherwise.
func (o *LineItemJurisTax) GetNonTaxableAmount() string {
	if o == nil || IsNil(o.NonTaxableAmount) {
		var ret string
		return ret
	}
	return *o.NonTaxableAmount
}

// GetNonTaxableAmountOk returns a tuple with the NonTaxableAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LineItemJurisTax) GetNonTaxableAmountOk() (*string, bool) {
	if o == nil || IsNil(o.NonTaxableAmount) {
		return nil, false
	}
	return o.NonTaxableAmount, true
}

// HasNonTaxableAmount returns a boolean if a field has been set.
func (o *LineItemJurisTax) HasNonTaxableAmount() bool {
	if o != nil && !IsNil(o.NonTaxableAmount) {
		return true
	}

	return false
}

// SetNonTaxableAmount gets a reference to the given string and assigns it to the NonTaxableAmount field.
func (o *LineItemJurisTax) SetNonTaxableAmount(v string) {
	o.NonTaxableAmount = &v
}

// GetExemptions returns the Exemptions field value if set, zero value otherwise.
func (o *LineItemJurisTax) GetExemptions() []LineItemJurisTaxExemptionsInner {
	if o == nil || IsNil(o.Exemptions) {
		var ret []LineItemJurisTaxExemptionsInner
		return ret
	}
	return o.Exemptions
}

// GetExemptionsOk returns a tuple with the Exemptions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LineItemJurisTax) GetExemptionsOk() ([]LineItemJurisTaxExemptionsInner, bool) {
	if o == nil || IsNil(o.Exemptions) {
		return nil, false
	}
	return o.Exemptions, true
}

// HasExemptions returns a boolean if a field has been set.
func (o *LineItemJurisTax) HasExemptions() bool {
	if o != nil && !IsNil(o.Exemptions) {
		return true
	}

	return false
}

// SetExemptions gets a reference to the given []LineItemJurisTaxExemptionsInner and assigns it to the Exemptions field.
func (o *LineItemJurisTax) SetExemptions(v []LineItemJurisTaxExemptionsInner) {
	o.Exemptions = v
}

// GetTaxableAmount returns the TaxableAmount field value if set, zero value otherwise.
func (o *LineItemJurisTax) GetTaxableAmount() string {
	if o == nil || IsNil(o.TaxableAmount) {
		var ret string
		return ret
	}
	return *o.TaxableAmount
}

// GetTaxableAmountOk returns a tuple with the TaxableAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LineItemJurisTax) GetTaxableAmountOk() (*string, bool) {
	if o == nil || IsNil(o.TaxableAmount) {
		return nil, false
	}
	return o.TaxableAmount, true
}

// HasTaxableAmount returns a boolean if a field has been set.
func (o *LineItemJurisTax) HasTaxableAmount() bool {
	if o != nil && !IsNil(o.TaxableAmount) {
		return true
	}

	return false
}

// SetTaxableAmount gets a reference to the given string and assigns it to the TaxableAmount field.
func (o *LineItemJurisTax) SetTaxableAmount(v string) {
	o.TaxableAmount = &v
}

// GetRate returns the Rate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LineItemJurisTax) GetRate() string {
	if o == nil || IsNil(o.Rate.Get()) {
		var ret string
		return ret
	}
	return *o.Rate.Get()
}

// GetRateOk returns a tuple with the Rate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LineItemJurisTax) GetRateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rate.Get(), o.Rate.IsSet()
}

// HasRate returns a boolean if a field has been set.
func (o *LineItemJurisTax) HasRate() bool {
	if o != nil && o.Rate.IsSet() {
		return true
	}

	return false
}

// SetRate gets a reference to the given NullableString and assigns it to the Rate field.
func (o *LineItemJurisTax) SetRate(v string) {
	o.Rate.Set(&v)
}
// SetRateNil sets the value for Rate to be an explicit nil
func (o *LineItemJurisTax) SetRateNil() {
	o.Rate.Set(nil)
}

// UnsetRate ensures that no value is present for Rate, not even an explicit nil
func (o *LineItemJurisTax) UnsetRate() {
	o.Rate.Unset()
}

// GetTaxAmount returns the TaxAmount field value if set, zero value otherwise.
func (o *LineItemJurisTax) GetTaxAmount() LineItemJurisTaxTaxAmount {
	if o == nil || IsNil(o.TaxAmount) {
		var ret LineItemJurisTaxTaxAmount
		return ret
	}
	return *o.TaxAmount
}

// GetTaxAmountOk returns a tuple with the TaxAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LineItemJurisTax) GetTaxAmountOk() (*LineItemJurisTaxTaxAmount, bool) {
	if o == nil || IsNil(o.TaxAmount) {
		return nil, false
	}
	return o.TaxAmount, true
}

// HasTaxAmount returns a boolean if a field has been set.
func (o *LineItemJurisTax) HasTaxAmount() bool {
	if o != nil && !IsNil(o.TaxAmount) {
		return true
	}

	return false
}

// SetTaxAmount gets a reference to the given LineItemJurisTaxTaxAmount and assigns it to the TaxAmount field.
func (o *LineItemJurisTax) SetTaxAmount(v LineItemJurisTaxTaxAmount) {
	o.TaxAmount = &v
}

func (o LineItemJurisTax) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LineItemJurisTax) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.NonTaxableAmount) {
		toSerialize["nonTaxableAmount"] = o.NonTaxableAmount
	}
	if !IsNil(o.Exemptions) {
		toSerialize["exemptions"] = o.Exemptions
	}
	if !IsNil(o.TaxableAmount) {
		toSerialize["taxableAmount"] = o.TaxableAmount
	}
	if o.Rate.IsSet() {
		toSerialize["rate"] = o.Rate.Get()
	}
	if !IsNil(o.TaxAmount) {
		toSerialize["taxAmount"] = o.TaxAmount
	}
	return toSerialize, nil
}

type NullableLineItemJurisTax struct {
	value *LineItemJurisTax
	isSet bool
}

func (v NullableLineItemJurisTax) Get() *LineItemJurisTax {
	return v.value
}

func (v *NullableLineItemJurisTax) Set(val *LineItemJurisTax) {
	v.value = val
	v.isSet = true
}

func (v NullableLineItemJurisTax) IsSet() bool {
	return v.isSet
}

func (v *NullableLineItemJurisTax) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLineItemJurisTax(val *LineItemJurisTax) *NullableLineItemJurisTax {
	return &NullableLineItemJurisTax{value: val, isSet: true}
}

func (v NullableLineItemJurisTax) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLineItemJurisTax) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


