/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FilingsRemoveTransactions200ResponseTransactionsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FilingsRemoveTransactions200ResponseTransactionsInner{}

// FilingsRemoveTransactions200ResponseTransactionsInner struct for FilingsRemoveTransactions200ResponseTransactionsInner
type FilingsRemoveTransactions200ResponseTransactionsInner struct {
	// The transaction ID.
	Id string `json:"id"`
	// `removed` if the transaction was removed from the filing; `error` if it could not be removed. 
	Status string `json:"status"`
	// Present only when `status` is `error`. `notFound` means the transaction was not in this filing (unknown, already removed, or in a different filing). 
	Reason *string `json:"reason,omitempty"`
}

type _FilingsRemoveTransactions200ResponseTransactionsInner FilingsRemoveTransactions200ResponseTransactionsInner

// NewFilingsRemoveTransactions200ResponseTransactionsInner instantiates a new FilingsRemoveTransactions200ResponseTransactionsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilingsRemoveTransactions200ResponseTransactionsInner(id string, status string) *FilingsRemoveTransactions200ResponseTransactionsInner {
	this := FilingsRemoveTransactions200ResponseTransactionsInner{}
	this.Id = id
	this.Status = status
	return &this
}

// NewFilingsRemoveTransactions200ResponseTransactionsInnerWithDefaults instantiates a new FilingsRemoveTransactions200ResponseTransactionsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilingsRemoveTransactions200ResponseTransactionsInnerWithDefaults() *FilingsRemoveTransactions200ResponseTransactionsInner {
	this := FilingsRemoveTransactions200ResponseTransactionsInner{}
	return &this
}

// GetId returns the Id field value
func (o *FilingsRemoveTransactions200ResponseTransactionsInner) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *FilingsRemoveTransactions200ResponseTransactionsInner) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *FilingsRemoveTransactions200ResponseTransactionsInner) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *FilingsRemoveTransactions200ResponseTransactionsInner) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *FilingsRemoveTransactions200ResponseTransactionsInner) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *FilingsRemoveTransactions200ResponseTransactionsInner) SetStatus(v string) {
	o.Status = v
}

// GetReason returns the Reason field value if set, zero value otherwise.
func (o *FilingsRemoveTransactions200ResponseTransactionsInner) GetReason() string {
	if o == nil || IsNil(o.Reason) {
		var ret string
		return ret
	}
	return *o.Reason
}

// GetReasonOk returns a tuple with the Reason field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilingsRemoveTransactions200ResponseTransactionsInner) GetReasonOk() (*string, bool) {
	if o == nil || IsNil(o.Reason) {
		return nil, false
	}
	return o.Reason, true
}

// HasReason returns a boolean if a field has been set.
func (o *FilingsRemoveTransactions200ResponseTransactionsInner) HasReason() bool {
	if o != nil && !IsNil(o.Reason) {
		return true
	}

	return false
}

// SetReason gets a reference to the given string and assigns it to the Reason field.
func (o *FilingsRemoveTransactions200ResponseTransactionsInner) SetReason(v string) {
	o.Reason = &v
}

func (o FilingsRemoveTransactions200ResponseTransactionsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FilingsRemoveTransactions200ResponseTransactionsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	if !IsNil(o.Reason) {
		toSerialize["reason"] = o.Reason
	}
	return toSerialize, nil
}

func (o *FilingsRemoveTransactions200ResponseTransactionsInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFilingsRemoveTransactions200ResponseTransactionsInner := _FilingsRemoveTransactions200ResponseTransactionsInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFilingsRemoveTransactions200ResponseTransactionsInner)

	if err != nil {
		return err
	}

	*o = FilingsRemoveTransactions200ResponseTransactionsInner(varFilingsRemoveTransactions200ResponseTransactionsInner)

	return err
}

type NullableFilingsRemoveTransactions200ResponseTransactionsInner struct {
	value *FilingsRemoveTransactions200ResponseTransactionsInner
	isSet bool
}

func (v NullableFilingsRemoveTransactions200ResponseTransactionsInner) Get() *FilingsRemoveTransactions200ResponseTransactionsInner {
	return v.value
}

func (v *NullableFilingsRemoveTransactions200ResponseTransactionsInner) Set(val *FilingsRemoveTransactions200ResponseTransactionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableFilingsRemoveTransactions200ResponseTransactionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableFilingsRemoveTransactions200ResponseTransactionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilingsRemoveTransactions200ResponseTransactionsInner(val *FilingsRemoveTransactions200ResponseTransactionsInner) *NullableFilingsRemoveTransactions200ResponseTransactionsInner {
	return &NullableFilingsRemoveTransactions200ResponseTransactionsInner{value: val, isSet: true}
}

func (v NullableFilingsRemoveTransactions200ResponseTransactionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilingsRemoveTransactions200ResponseTransactionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


