/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FilingsListTransactionIdsRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FilingsListTransactionIdsRequest{}

// FilingsListTransactionIdsRequest struct for FilingsListTransactionIdsRequest
type FilingsListTransactionIdsRequest struct {
	// The maximum number of transaction IDs to return.
	Limit *int32 `json:"limit,omitempty"`
	// The cursor to use for pagination. This is the value of the `nextCursor` field returned from the previous page.
	Cursor *string `json:"cursor,omitempty"`
}

// NewFilingsListTransactionIdsRequest instantiates a new FilingsListTransactionIdsRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilingsListTransactionIdsRequest() *FilingsListTransactionIdsRequest {
	this := FilingsListTransactionIdsRequest{}
	var limit int32 = 100
	this.Limit = &limit
	return &this
}

// NewFilingsListTransactionIdsRequestWithDefaults instantiates a new FilingsListTransactionIdsRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilingsListTransactionIdsRequestWithDefaults() *FilingsListTransactionIdsRequest {
	this := FilingsListTransactionIdsRequest{}
	var limit int32 = 100
	this.Limit = &limit
	return &this
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *FilingsListTransactionIdsRequest) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilingsListTransactionIdsRequest) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *FilingsListTransactionIdsRequest) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *FilingsListTransactionIdsRequest) SetLimit(v int32) {
	o.Limit = &v
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *FilingsListTransactionIdsRequest) GetCursor() string {
	if o == nil || IsNil(o.Cursor) {
		var ret string
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FilingsListTransactionIdsRequest) GetCursorOk() (*string, bool) {
	if o == nil || IsNil(o.Cursor) {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *FilingsListTransactionIdsRequest) HasCursor() bool {
	if o != nil && !IsNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given string and assigns it to the Cursor field.
func (o *FilingsListTransactionIdsRequest) SetCursor(v string) {
	o.Cursor = &v
}

func (o FilingsListTransactionIdsRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FilingsListTransactionIdsRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}
	return toSerialize, nil
}

type NullableFilingsListTransactionIdsRequest struct {
	value *FilingsListTransactionIdsRequest
	isSet bool
}

func (v NullableFilingsListTransactionIdsRequest) Get() *FilingsListTransactionIdsRequest {
	return v.value
}

func (v *NullableFilingsListTransactionIdsRequest) Set(val *FilingsListTransactionIdsRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableFilingsListTransactionIdsRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableFilingsListTransactionIdsRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilingsListTransactionIdsRequest(val *FilingsListTransactionIdsRequest) *NullableFilingsListTransactionIdsRequest {
	return &NullableFilingsListTransactionIdsRequest{value: val, isSet: true}
}

func (v NullableFilingsListTransactionIdsRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilingsListTransactionIdsRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


