/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ResolveAddressSuccess type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResolveAddressSuccess{}

// ResolveAddressSuccess struct for ResolveAddressSuccess
type ResolveAddressSuccess struct {
	// The resolved customer address. For addresses in the United States and Canada the full address is returned; for all other countries only the country is populated.
	ResolvedAddress CustomerAddress `json:"resolvedAddress"`
	// The taxable jurisdiction(s) the address resolves to.
	Jurisdictions []ResolveAddressSuccessJurisdictionsInner `json:"jurisdictions"`
}

type _ResolveAddressSuccess ResolveAddressSuccess

// NewResolveAddressSuccess instantiates a new ResolveAddressSuccess object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResolveAddressSuccess(resolvedAddress CustomerAddress, jurisdictions []ResolveAddressSuccessJurisdictionsInner) *ResolveAddressSuccess {
	this := ResolveAddressSuccess{}
	this.ResolvedAddress = resolvedAddress
	this.Jurisdictions = jurisdictions
	return &this
}

// NewResolveAddressSuccessWithDefaults instantiates a new ResolveAddressSuccess object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResolveAddressSuccessWithDefaults() *ResolveAddressSuccess {
	this := ResolveAddressSuccess{}
	return &this
}

// GetResolvedAddress returns the ResolvedAddress field value
func (o *ResolveAddressSuccess) GetResolvedAddress() CustomerAddress {
	if o == nil {
		var ret CustomerAddress
		return ret
	}

	return o.ResolvedAddress
}

// GetResolvedAddressOk returns a tuple with the ResolvedAddress field value
// and a boolean to check if the value has been set.
func (o *ResolveAddressSuccess) GetResolvedAddressOk() (*CustomerAddress, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ResolvedAddress, true
}

// SetResolvedAddress sets field value
func (o *ResolveAddressSuccess) SetResolvedAddress(v CustomerAddress) {
	o.ResolvedAddress = v
}

// GetJurisdictions returns the Jurisdictions field value
func (o *ResolveAddressSuccess) GetJurisdictions() []ResolveAddressSuccessJurisdictionsInner {
	if o == nil {
		var ret []ResolveAddressSuccessJurisdictionsInner
		return ret
	}

	return o.Jurisdictions
}

// GetJurisdictionsOk returns a tuple with the Jurisdictions field value
// and a boolean to check if the value has been set.
func (o *ResolveAddressSuccess) GetJurisdictionsOk() ([]ResolveAddressSuccessJurisdictionsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Jurisdictions, true
}

// SetJurisdictions sets field value
func (o *ResolveAddressSuccess) SetJurisdictions(v []ResolveAddressSuccessJurisdictionsInner) {
	o.Jurisdictions = v
}

func (o ResolveAddressSuccess) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResolveAddressSuccess) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["resolvedAddress"] = o.ResolvedAddress
	toSerialize["jurisdictions"] = o.Jurisdictions
	return toSerialize, nil
}

func (o *ResolveAddressSuccess) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"resolvedAddress",
		"jurisdictions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varResolveAddressSuccess := _ResolveAddressSuccess{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varResolveAddressSuccess)

	if err != nil {
		return err
	}

	*o = ResolveAddressSuccess(varResolveAddressSuccess)

	return err
}

type NullableResolveAddressSuccess struct {
	value *ResolveAddressSuccess
	isSet bool
}

func (v NullableResolveAddressSuccess) Get() *ResolveAddressSuccess {
	return v.value
}

func (v *NullableResolveAddressSuccess) Set(val *ResolveAddressSuccess) {
	v.value = val
	v.isSet = true
}

func (v NullableResolveAddressSuccess) IsSet() bool {
	return v.isSet
}

func (v *NullableResolveAddressSuccess) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResolveAddressSuccess(val *ResolveAddressSuccess) *NullableResolveAddressSuccess {
	return &NullableResolveAddressSuccess{value: val, isSet: true}
}

func (v NullableResolveAddressSuccess) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResolveAddressSuccess) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


