/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the InlineObject3FilingsInnerPeriod type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InlineObject3FilingsInnerPeriod{}

// InlineObject3FilingsInnerPeriod The period of the filing.
type InlineObject3FilingsInnerPeriod struct {
	// The beginning date of the filing period.
	Begin *string `json:"begin,omitempty"`
	// The end date of the filing period (inclusive).
	EndInclusive *string `json:"endInclusive,omitempty"`
}

// NewInlineObject3FilingsInnerPeriod instantiates a new InlineObject3FilingsInnerPeriod object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject3FilingsInnerPeriod() *InlineObject3FilingsInnerPeriod {
	this := InlineObject3FilingsInnerPeriod{}
	return &this
}

// NewInlineObject3FilingsInnerPeriodWithDefaults instantiates a new InlineObject3FilingsInnerPeriod object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject3FilingsInnerPeriodWithDefaults() *InlineObject3FilingsInnerPeriod {
	this := InlineObject3FilingsInnerPeriod{}
	return &this
}

// GetBegin returns the Begin field value if set, zero value otherwise.
func (o *InlineObject3FilingsInnerPeriod) GetBegin() string {
	if o == nil || IsNil(o.Begin) {
		var ret string
		return ret
	}
	return *o.Begin
}

// GetBeginOk returns a tuple with the Begin field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject3FilingsInnerPeriod) GetBeginOk() (*string, bool) {
	if o == nil || IsNil(o.Begin) {
		return nil, false
	}
	return o.Begin, true
}

// HasBegin returns a boolean if a field has been set.
func (o *InlineObject3FilingsInnerPeriod) HasBegin() bool {
	if o != nil && !IsNil(o.Begin) {
		return true
	}

	return false
}

// SetBegin gets a reference to the given string and assigns it to the Begin field.
func (o *InlineObject3FilingsInnerPeriod) SetBegin(v string) {
	o.Begin = &v
}

// GetEndInclusive returns the EndInclusive field value if set, zero value otherwise.
func (o *InlineObject3FilingsInnerPeriod) GetEndInclusive() string {
	if o == nil || IsNil(o.EndInclusive) {
		var ret string
		return ret
	}
	return *o.EndInclusive
}

// GetEndInclusiveOk returns a tuple with the EndInclusive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject3FilingsInnerPeriod) GetEndInclusiveOk() (*string, bool) {
	if o == nil || IsNil(o.EndInclusive) {
		return nil, false
	}
	return o.EndInclusive, true
}

// HasEndInclusive returns a boolean if a field has been set.
func (o *InlineObject3FilingsInnerPeriod) HasEndInclusive() bool {
	if o != nil && !IsNil(o.EndInclusive) {
		return true
	}

	return false
}

// SetEndInclusive gets a reference to the given string and assigns it to the EndInclusive field.
func (o *InlineObject3FilingsInnerPeriod) SetEndInclusive(v string) {
	o.EndInclusive = &v
}

func (o InlineObject3FilingsInnerPeriod) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InlineObject3FilingsInnerPeriod) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Begin) {
		toSerialize["begin"] = o.Begin
	}
	if !IsNil(o.EndInclusive) {
		toSerialize["endInclusive"] = o.EndInclusive
	}
	return toSerialize, nil
}

type NullableInlineObject3FilingsInnerPeriod struct {
	value *InlineObject3FilingsInnerPeriod
	isSet bool
}

func (v NullableInlineObject3FilingsInnerPeriod) Get() *InlineObject3FilingsInnerPeriod {
	return v.value
}

func (v *NullableInlineObject3FilingsInnerPeriod) Set(val *InlineObject3FilingsInnerPeriod) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject3FilingsInnerPeriod) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject3FilingsInnerPeriod) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject3FilingsInnerPeriod(val *InlineObject3FilingsInnerPeriod) *NullableInlineObject3FilingsInnerPeriod {
	return &NullableInlineObject3FilingsInnerPeriod{value: val, isSet: true}
}

func (v NullableInlineObject3FilingsInnerPeriod) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject3FilingsInnerPeriod) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


