/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// TransactionsListRequestFilter - The filter to apply to the returned transactions.
type TransactionsListRequestFilter struct {
	FilingInfoFilter *FilingInfoFilter
	LastModifiedAfterFilter *LastModifiedAfterFilter
}

// FilingInfoFilterAsTransactionsListRequestFilter is a convenience function that returns FilingInfoFilter wrapped in TransactionsListRequestFilter
func FilingInfoFilterAsTransactionsListRequestFilter(v *FilingInfoFilter) TransactionsListRequestFilter {
	return TransactionsListRequestFilter{
		FilingInfoFilter: v,
	}
}

// LastModifiedAfterFilterAsTransactionsListRequestFilter is a convenience function that returns LastModifiedAfterFilter wrapped in TransactionsListRequestFilter
func LastModifiedAfterFilterAsTransactionsListRequestFilter(v *LastModifiedAfterFilter) TransactionsListRequestFilter {
	return TransactionsListRequestFilter{
		LastModifiedAfterFilter: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *TransactionsListRequestFilter) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into FilingInfoFilter
	err = newStrictDecoder(data).Decode(&dst.FilingInfoFilter)
	if err == nil {
		jsonFilingInfoFilter, _ := json.Marshal(dst.FilingInfoFilter)
		if string(jsonFilingInfoFilter) == "{}" { // empty struct
			dst.FilingInfoFilter = nil
		} else {
			if err = validator.Validate(dst.FilingInfoFilter); err != nil {
				dst.FilingInfoFilter = nil
			} else {
				match++
			}
		}
	} else {
		dst.FilingInfoFilter = nil
	}

	// try to unmarshal data into LastModifiedAfterFilter
	err = newStrictDecoder(data).Decode(&dst.LastModifiedAfterFilter)
	if err == nil {
		jsonLastModifiedAfterFilter, _ := json.Marshal(dst.LastModifiedAfterFilter)
		if string(jsonLastModifiedAfterFilter) == "{}" { // empty struct
			dst.LastModifiedAfterFilter = nil
		} else {
			if err = validator.Validate(dst.LastModifiedAfterFilter); err != nil {
				dst.LastModifiedAfterFilter = nil
			} else {
				match++
			}
		}
	} else {
		dst.LastModifiedAfterFilter = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.FilingInfoFilter = nil
		dst.LastModifiedAfterFilter = nil

		return fmt.Errorf("data matches more than one schema in oneOf(TransactionsListRequestFilter)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(TransactionsListRequestFilter)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src TransactionsListRequestFilter) MarshalJSON() ([]byte, error) {
	if src.FilingInfoFilter != nil {
		return json.Marshal(&src.FilingInfoFilter)
	}

	if src.LastModifiedAfterFilter != nil {
		return json.Marshal(&src.LastModifiedAfterFilter)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *TransactionsListRequestFilter) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.FilingInfoFilter != nil {
		return obj.FilingInfoFilter
	}

	if obj.LastModifiedAfterFilter != nil {
		return obj.LastModifiedAfterFilter
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj TransactionsListRequestFilter) GetActualInstanceValue() (interface{}) {
	if obj.FilingInfoFilter != nil {
		return *obj.FilingInfoFilter
	}

	if obj.LastModifiedAfterFilter != nil {
		return *obj.LastModifiedAfterFilter
	}

	// all schemas are nil
	return nil
}

type NullableTransactionsListRequestFilter struct {
	value *TransactionsListRequestFilter
	isSet bool
}

func (v NullableTransactionsListRequestFilter) Get() *TransactionsListRequestFilter {
	return v.value
}

func (v *NullableTransactionsListRequestFilter) Set(val *TransactionsListRequestFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableTransactionsListRequestFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableTransactionsListRequestFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTransactionsListRequestFilter(val *TransactionsListRequestFilter) *NullableTransactionsListRequestFilter {
	return &NullableTransactionsListRequestFilter{value: val, isSet: true}
}

func (v NullableTransactionsListRequestFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTransactionsListRequestFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


