/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TaxAmountDue type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaxAmountDue{}

// TaxAmountDue The tax amount due in the smallest denomination of the currency (e.g. cents or pennies).
type TaxAmountDue struct {
	// The inclusive tax amount in the smallest denomination of the currency (e.g. cents or pennies).
	Inclusive *string `json:"inclusive,omitempty"`
	// The exclusive tax amount in the smallest denomination of the currency (e.g. cents or pennies).
	Exclusive *string `json:"exclusive,omitempty"`
	// The total tax amount in the smallest denomination of the currency (e.g. cents or pennies).
	Total *string `json:"total,omitempty"`
}

// NewTaxAmountDue instantiates a new TaxAmountDue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaxAmountDue() *TaxAmountDue {
	this := TaxAmountDue{}
	return &this
}

// NewTaxAmountDueWithDefaults instantiates a new TaxAmountDue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaxAmountDueWithDefaults() *TaxAmountDue {
	this := TaxAmountDue{}
	return &this
}

// GetInclusive returns the Inclusive field value if set, zero value otherwise.
func (o *TaxAmountDue) GetInclusive() string {
	if o == nil || IsNil(o.Inclusive) {
		var ret string
		return ret
	}
	return *o.Inclusive
}

// GetInclusiveOk returns a tuple with the Inclusive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaxAmountDue) GetInclusiveOk() (*string, bool) {
	if o == nil || IsNil(o.Inclusive) {
		return nil, false
	}
	return o.Inclusive, true
}

// HasInclusive returns a boolean if a field has been set.
func (o *TaxAmountDue) HasInclusive() bool {
	if o != nil && !IsNil(o.Inclusive) {
		return true
	}

	return false
}

// SetInclusive gets a reference to the given string and assigns it to the Inclusive field.
func (o *TaxAmountDue) SetInclusive(v string) {
	o.Inclusive = &v
}

// GetExclusive returns the Exclusive field value if set, zero value otherwise.
func (o *TaxAmountDue) GetExclusive() string {
	if o == nil || IsNil(o.Exclusive) {
		var ret string
		return ret
	}
	return *o.Exclusive
}

// GetExclusiveOk returns a tuple with the Exclusive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaxAmountDue) GetExclusiveOk() (*string, bool) {
	if o == nil || IsNil(o.Exclusive) {
		return nil, false
	}
	return o.Exclusive, true
}

// HasExclusive returns a boolean if a field has been set.
func (o *TaxAmountDue) HasExclusive() bool {
	if o != nil && !IsNil(o.Exclusive) {
		return true
	}

	return false
}

// SetExclusive gets a reference to the given string and assigns it to the Exclusive field.
func (o *TaxAmountDue) SetExclusive(v string) {
	o.Exclusive = &v
}

// GetTotal returns the Total field value if set, zero value otherwise.
func (o *TaxAmountDue) GetTotal() string {
	if o == nil || IsNil(o.Total) {
		var ret string
		return ret
	}
	return *o.Total
}

// GetTotalOk returns a tuple with the Total field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaxAmountDue) GetTotalOk() (*string, bool) {
	if o == nil || IsNil(o.Total) {
		return nil, false
	}
	return o.Total, true
}

// HasTotal returns a boolean if a field has been set.
func (o *TaxAmountDue) HasTotal() bool {
	if o != nil && !IsNil(o.Total) {
		return true
	}

	return false
}

// SetTotal gets a reference to the given string and assigns it to the Total field.
func (o *TaxAmountDue) SetTotal(v string) {
	o.Total = &v
}

func (o TaxAmountDue) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaxAmountDue) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Inclusive) {
		toSerialize["inclusive"] = o.Inclusive
	}
	if !IsNil(o.Exclusive) {
		toSerialize["exclusive"] = o.Exclusive
	}
	if !IsNil(o.Total) {
		toSerialize["total"] = o.Total
	}
	return toSerialize, nil
}

type NullableTaxAmountDue struct {
	value *TaxAmountDue
	isSet bool
}

func (v NullableTaxAmountDue) Get() *TaxAmountDue {
	return v.value
}

func (v *NullableTaxAmountDue) Set(val *TaxAmountDue) {
	v.value = val
	v.isSet = true
}

func (v NullableTaxAmountDue) IsSet() bool {
	return v.isSet
}

func (v *NullableTaxAmountDue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaxAmountDue(val *TaxAmountDue) *NullableTaxAmountDue {
	return &NullableTaxAmountDue{value: val, isSet: true}
}

func (v NullableTaxAmountDue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaxAmountDue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


