/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the CustomerCertificateResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CustomerCertificateResponse{}

// CustomerCertificateResponse struct for CustomerCertificateResponse
type CustomerCertificateResponse struct {
	// The Anrok-assigned ID of the certificate.
	Id string `json:"id"`
	// The current status of the certificate.  - `active`: the certificate is valid. - `expiringSoon`: the certificate is valid but expires within 60 days in at least one jurisdiction. - `expired`: the certificate has expired in every jurisdiction it covers. - `archived`: the certificate has been archived. 
	Status string `json:"status"`
	// The Anrok customer ID of the customer the certificate belongs to.
	CustomerId string `json:"customerId"`
	// The name of the customer.
	CustomerName string `json:"customerName"`
	// The time at which the certificate was created in Anrok.
	CreatedTime time.Time `json:"createdTime"`
	// Effective date of the certificate.
	EffectiveDateBegin string `json:"effectiveDateBegin"`
	// The earliest expiration date across all jurisdictions covered by the certificate. Null if no jurisdiction has an expiration date set.
	ExpiryDate NullableString `json:"expiryDate"`
	// Certificate exemption number.
	ExemptionNumber string `json:"exemptionNumber"`
	// Optional internal notes.
	Notes string `json:"notes"`
	// The type of exemption the certificate represents. Null if no type has been recorded.  - `agricultural`: agricultural use. - `directPay`: direct pay permit. - `educational`: educational institution. - `energy`: energy-related exemption. - `governmentFederal`: federal government entity. - `governmentOther`: other government entity. - `governmentState`: state government entity. - `healthcare`: healthcare organization. - `manufacturing`: used in manufacturing. - `nativeAmericanTribal`: Native American tribal entity. - `nonprofit`: nonprofit organization. - `other`: other exemption type. - `religious`: religious organization. - `resale`: purchased for resale. - `researchDevelopment`: research and development use. 
	Type NullableString `json:"type"`
	// The jurisdictions to which the certificate applies.
	Jurises []CustomerCertificateJurisResponse `json:"jurises"`
}

type _CustomerCertificateResponse CustomerCertificateResponse

// NewCustomerCertificateResponse instantiates a new CustomerCertificateResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCustomerCertificateResponse(id string, status string, customerId string, customerName string, createdTime time.Time, effectiveDateBegin string, expiryDate NullableString, exemptionNumber string, notes string, type_ NullableString, jurises []CustomerCertificateJurisResponse) *CustomerCertificateResponse {
	this := CustomerCertificateResponse{}
	this.Id = id
	this.Status = status
	this.CustomerId = customerId
	this.CustomerName = customerName
	this.CreatedTime = createdTime
	this.EffectiveDateBegin = effectiveDateBegin
	this.ExpiryDate = expiryDate
	this.ExemptionNumber = exemptionNumber
	this.Notes = notes
	this.Type = type_
	this.Jurises = jurises
	return &this
}

// NewCustomerCertificateResponseWithDefaults instantiates a new CustomerCertificateResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCustomerCertificateResponseWithDefaults() *CustomerCertificateResponse {
	this := CustomerCertificateResponse{}
	return &this
}

// GetId returns the Id field value
func (o *CustomerCertificateResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *CustomerCertificateResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *CustomerCertificateResponse) SetId(v string) {
	o.Id = v
}

// GetStatus returns the Status field value
func (o *CustomerCertificateResponse) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *CustomerCertificateResponse) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *CustomerCertificateResponse) SetStatus(v string) {
	o.Status = v
}

// GetCustomerId returns the CustomerId field value
func (o *CustomerCertificateResponse) GetCustomerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value
// and a boolean to check if the value has been set.
func (o *CustomerCertificateResponse) GetCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerId, true
}

// SetCustomerId sets field value
func (o *CustomerCertificateResponse) SetCustomerId(v string) {
	o.CustomerId = v
}

// GetCustomerName returns the CustomerName field value
func (o *CustomerCertificateResponse) GetCustomerName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerName
}

// GetCustomerNameOk returns a tuple with the CustomerName field value
// and a boolean to check if the value has been set.
func (o *CustomerCertificateResponse) GetCustomerNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerName, true
}

// SetCustomerName sets field value
func (o *CustomerCertificateResponse) SetCustomerName(v string) {
	o.CustomerName = v
}

// GetCreatedTime returns the CreatedTime field value
func (o *CustomerCertificateResponse) GetCreatedTime() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.CreatedTime
}

// GetCreatedTimeOk returns a tuple with the CreatedTime field value
// and a boolean to check if the value has been set.
func (o *CustomerCertificateResponse) GetCreatedTimeOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedTime, true
}

// SetCreatedTime sets field value
func (o *CustomerCertificateResponse) SetCreatedTime(v time.Time) {
	o.CreatedTime = v
}

// GetEffectiveDateBegin returns the EffectiveDateBegin field value
func (o *CustomerCertificateResponse) GetEffectiveDateBegin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EffectiveDateBegin
}

// GetEffectiveDateBeginOk returns a tuple with the EffectiveDateBegin field value
// and a boolean to check if the value has been set.
func (o *CustomerCertificateResponse) GetEffectiveDateBeginOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EffectiveDateBegin, true
}

// SetEffectiveDateBegin sets field value
func (o *CustomerCertificateResponse) SetEffectiveDateBegin(v string) {
	o.EffectiveDateBegin = v
}

// GetExpiryDate returns the ExpiryDate field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CustomerCertificateResponse) GetExpiryDate() string {
	if o == nil || o.ExpiryDate.Get() == nil {
		var ret string
		return ret
	}

	return *o.ExpiryDate.Get()
}

// GetExpiryDateOk returns a tuple with the ExpiryDate field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerCertificateResponse) GetExpiryDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.ExpiryDate.Get(), o.ExpiryDate.IsSet()
}

// SetExpiryDate sets field value
func (o *CustomerCertificateResponse) SetExpiryDate(v string) {
	o.ExpiryDate.Set(&v)
}

// GetExemptionNumber returns the ExemptionNumber field value
func (o *CustomerCertificateResponse) GetExemptionNumber() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExemptionNumber
}

// GetExemptionNumberOk returns a tuple with the ExemptionNumber field value
// and a boolean to check if the value has been set.
func (o *CustomerCertificateResponse) GetExemptionNumberOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExemptionNumber, true
}

// SetExemptionNumber sets field value
func (o *CustomerCertificateResponse) SetExemptionNumber(v string) {
	o.ExemptionNumber = v
}

// GetNotes returns the Notes field value
func (o *CustomerCertificateResponse) GetNotes() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Notes
}

// GetNotesOk returns a tuple with the Notes field value
// and a boolean to check if the value has been set.
func (o *CustomerCertificateResponse) GetNotesOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Notes, true
}

// SetNotes sets field value
func (o *CustomerCertificateResponse) SetNotes(v string) {
	o.Notes = v
}

// GetType returns the Type field value
// If the value is explicit nil, the zero value for string will be returned
func (o *CustomerCertificateResponse) GetType() string {
	if o == nil || o.Type.Get() == nil {
		var ret string
		return ret
	}

	return *o.Type.Get()
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *CustomerCertificateResponse) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Type.Get(), o.Type.IsSet()
}

// SetType sets field value
func (o *CustomerCertificateResponse) SetType(v string) {
	o.Type.Set(&v)
}

// GetJurises returns the Jurises field value
func (o *CustomerCertificateResponse) GetJurises() []CustomerCertificateJurisResponse {
	if o == nil {
		var ret []CustomerCertificateJurisResponse
		return ret
	}

	return o.Jurises
}

// GetJurisesOk returns a tuple with the Jurises field value
// and a boolean to check if the value has been set.
func (o *CustomerCertificateResponse) GetJurisesOk() ([]CustomerCertificateJurisResponse, bool) {
	if o == nil {
		return nil, false
	}
	return o.Jurises, true
}

// SetJurises sets field value
func (o *CustomerCertificateResponse) SetJurises(v []CustomerCertificateJurisResponse) {
	o.Jurises = v
}

func (o CustomerCertificateResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CustomerCertificateResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["status"] = o.Status
	toSerialize["customerId"] = o.CustomerId
	toSerialize["customerName"] = o.CustomerName
	toSerialize["createdTime"] = o.CreatedTime
	toSerialize["effectiveDateBegin"] = o.EffectiveDateBegin
	toSerialize["expiryDate"] = o.ExpiryDate.Get()
	toSerialize["exemptionNumber"] = o.ExemptionNumber
	toSerialize["notes"] = o.Notes
	toSerialize["type"] = o.Type.Get()
	toSerialize["jurises"] = o.Jurises
	return toSerialize, nil
}

func (o *CustomerCertificateResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"status",
		"customerId",
		"customerName",
		"createdTime",
		"effectiveDateBegin",
		"expiryDate",
		"exemptionNumber",
		"notes",
		"type",
		"jurises",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCustomerCertificateResponse := _CustomerCertificateResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCustomerCertificateResponse)

	if err != nil {
		return err
	}

	*o = CustomerCertificateResponse(varCustomerCertificateResponse)

	return err
}

type NullableCustomerCertificateResponse struct {
	value *CustomerCertificateResponse
	isSet bool
}

func (v NullableCustomerCertificateResponse) Get() *CustomerCertificateResponse {
	return v.value
}

func (v *NullableCustomerCertificateResponse) Set(val *CustomerCertificateResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCustomerCertificateResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCustomerCertificateResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCustomerCertificateResponse(val *CustomerCertificateResponse) *NullableCustomerCertificateResponse {
	return &NullableCustomerCertificateResponse{value: val, isSet: true}
}

func (v NullableCustomerCertificateResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCustomerCertificateResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


