/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the InlineObject9TransactionsWithConversionRatesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InlineObject9TransactionsWithConversionRatesInner{}

// InlineObject9TransactionsWithConversionRatesInner struct for InlineObject9TransactionsWithConversionRatesInner
type InlineObject9TransactionsWithConversionRatesInner struct {
	// The ID of the transaction.
	Id *string `json:"id,omitempty"`
	// The three letter ISO currency code of the transaction.
	FromCurrency *string `json:"fromCurrency,omitempty"`
	// The three letter ISO currency code of the filing.
	ToCurrency *string `json:"toCurrency,omitempty"`
	// The conversion rate used to convert amounts from the transaction currency to the filing currency, as a decimal number formatted as a string. This is null when the transaction currency is the same as the filing currency and no conversion was applied.
	Rate NullableString `json:"rate,omitempty"`
}

// NewInlineObject9TransactionsWithConversionRatesInner instantiates a new InlineObject9TransactionsWithConversionRatesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject9TransactionsWithConversionRatesInner() *InlineObject9TransactionsWithConversionRatesInner {
	this := InlineObject9TransactionsWithConversionRatesInner{}
	return &this
}

// NewInlineObject9TransactionsWithConversionRatesInnerWithDefaults instantiates a new InlineObject9TransactionsWithConversionRatesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject9TransactionsWithConversionRatesInnerWithDefaults() *InlineObject9TransactionsWithConversionRatesInner {
	this := InlineObject9TransactionsWithConversionRatesInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *InlineObject9TransactionsWithConversionRatesInner) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject9TransactionsWithConversionRatesInner) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *InlineObject9TransactionsWithConversionRatesInner) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *InlineObject9TransactionsWithConversionRatesInner) SetId(v string) {
	o.Id = &v
}

// GetFromCurrency returns the FromCurrency field value if set, zero value otherwise.
func (o *InlineObject9TransactionsWithConversionRatesInner) GetFromCurrency() string {
	if o == nil || IsNil(o.FromCurrency) {
		var ret string
		return ret
	}
	return *o.FromCurrency
}

// GetFromCurrencyOk returns a tuple with the FromCurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject9TransactionsWithConversionRatesInner) GetFromCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.FromCurrency) {
		return nil, false
	}
	return o.FromCurrency, true
}

// HasFromCurrency returns a boolean if a field has been set.
func (o *InlineObject9TransactionsWithConversionRatesInner) HasFromCurrency() bool {
	if o != nil && !IsNil(o.FromCurrency) {
		return true
	}

	return false
}

// SetFromCurrency gets a reference to the given string and assigns it to the FromCurrency field.
func (o *InlineObject9TransactionsWithConversionRatesInner) SetFromCurrency(v string) {
	o.FromCurrency = &v
}

// GetToCurrency returns the ToCurrency field value if set, zero value otherwise.
func (o *InlineObject9TransactionsWithConversionRatesInner) GetToCurrency() string {
	if o == nil || IsNil(o.ToCurrency) {
		var ret string
		return ret
	}
	return *o.ToCurrency
}

// GetToCurrencyOk returns a tuple with the ToCurrency field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject9TransactionsWithConversionRatesInner) GetToCurrencyOk() (*string, bool) {
	if o == nil || IsNil(o.ToCurrency) {
		return nil, false
	}
	return o.ToCurrency, true
}

// HasToCurrency returns a boolean if a field has been set.
func (o *InlineObject9TransactionsWithConversionRatesInner) HasToCurrency() bool {
	if o != nil && !IsNil(o.ToCurrency) {
		return true
	}

	return false
}

// SetToCurrency gets a reference to the given string and assigns it to the ToCurrency field.
func (o *InlineObject9TransactionsWithConversionRatesInner) SetToCurrency(v string) {
	o.ToCurrency = &v
}

// GetRate returns the Rate field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *InlineObject9TransactionsWithConversionRatesInner) GetRate() string {
	if o == nil || IsNil(o.Rate.Get()) {
		var ret string
		return ret
	}
	return *o.Rate.Get()
}

// GetRateOk returns a tuple with the Rate field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *InlineObject9TransactionsWithConversionRatesInner) GetRateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Rate.Get(), o.Rate.IsSet()
}

// HasRate returns a boolean if a field has been set.
func (o *InlineObject9TransactionsWithConversionRatesInner) HasRate() bool {
	if o != nil && o.Rate.IsSet() {
		return true
	}

	return false
}

// SetRate gets a reference to the given NullableString and assigns it to the Rate field.
func (o *InlineObject9TransactionsWithConversionRatesInner) SetRate(v string) {
	o.Rate.Set(&v)
}
// SetRateNil sets the value for Rate to be an explicit nil
func (o *InlineObject9TransactionsWithConversionRatesInner) SetRateNil() {
	o.Rate.Set(nil)
}

// UnsetRate ensures that no value is present for Rate, not even an explicit nil
func (o *InlineObject9TransactionsWithConversionRatesInner) UnsetRate() {
	o.Rate.Unset()
}

func (o InlineObject9TransactionsWithConversionRatesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InlineObject9TransactionsWithConversionRatesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.FromCurrency) {
		toSerialize["fromCurrency"] = o.FromCurrency
	}
	if !IsNil(o.ToCurrency) {
		toSerialize["toCurrency"] = o.ToCurrency
	}
	if o.Rate.IsSet() {
		toSerialize["rate"] = o.Rate.Get()
	}
	return toSerialize, nil
}

type NullableInlineObject9TransactionsWithConversionRatesInner struct {
	value *InlineObject9TransactionsWithConversionRatesInner
	isSet bool
}

func (v NullableInlineObject9TransactionsWithConversionRatesInner) Get() *InlineObject9TransactionsWithConversionRatesInner {
	return v.value
}

func (v *NullableInlineObject9TransactionsWithConversionRatesInner) Set(val *InlineObject9TransactionsWithConversionRatesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject9TransactionsWithConversionRatesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject9TransactionsWithConversionRatesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject9TransactionsWithConversionRatesInner(val *InlineObject9TransactionsWithConversionRatesInner) *NullableInlineObject9TransactionsWithConversionRatesInner {
	return &NullableInlineObject9TransactionsWithConversionRatesInner{value: val, isSet: true}
}

func (v NullableInlineObject9TransactionsWithConversionRatesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject9TransactionsWithConversionRatesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


