/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// ProductResponse - A product in your Anrok account. The shape depends on `productType`. `regular` products include an `externalId`; `default` products include `defaultForSellerIntegrationId` and `defaultForLineItemType`.
type ProductResponse struct {
	DefaultProduct *DefaultProduct
	RegularProduct *RegularProduct
}

// DefaultProductAsProductResponse is a convenience function that returns DefaultProduct wrapped in ProductResponse
func DefaultProductAsProductResponse(v *DefaultProduct) ProductResponse {
	return ProductResponse{
		DefaultProduct: v,
	}
}

// RegularProductAsProductResponse is a convenience function that returns RegularProduct wrapped in ProductResponse
func RegularProductAsProductResponse(v *RegularProduct) ProductResponse {
	return ProductResponse{
		RegularProduct: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *ProductResponse) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into DefaultProduct
	err = newStrictDecoder(data).Decode(&dst.DefaultProduct)
	if err == nil {
		jsonDefaultProduct, _ := json.Marshal(dst.DefaultProduct)
		if string(jsonDefaultProduct) == "{}" { // empty struct
			dst.DefaultProduct = nil
		} else {
			if err = validator.Validate(dst.DefaultProduct); err != nil {
				dst.DefaultProduct = nil
			} else {
				match++
			}
		}
	} else {
		dst.DefaultProduct = nil
	}

	// try to unmarshal data into RegularProduct
	err = newStrictDecoder(data).Decode(&dst.RegularProduct)
	if err == nil {
		jsonRegularProduct, _ := json.Marshal(dst.RegularProduct)
		if string(jsonRegularProduct) == "{}" { // empty struct
			dst.RegularProduct = nil
		} else {
			if err = validator.Validate(dst.RegularProduct); err != nil {
				dst.RegularProduct = nil
			} else {
				match++
			}
		}
	} else {
		dst.RegularProduct = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.DefaultProduct = nil
		dst.RegularProduct = nil

		return fmt.Errorf("data matches more than one schema in oneOf(ProductResponse)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(ProductResponse)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src ProductResponse) MarshalJSON() ([]byte, error) {
	if src.DefaultProduct != nil {
		return json.Marshal(&src.DefaultProduct)
	}

	if src.RegularProduct != nil {
		return json.Marshal(&src.RegularProduct)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *ProductResponse) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.DefaultProduct != nil {
		return obj.DefaultProduct
	}

	if obj.RegularProduct != nil {
		return obj.RegularProduct
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj ProductResponse) GetActualInstanceValue() (interface{}) {
	if obj.DefaultProduct != nil {
		return *obj.DefaultProduct
	}

	if obj.RegularProduct != nil {
		return *obj.RegularProduct
	}

	// all schemas are nil
	return nil
}

type NullableProductResponse struct {
	value *ProductResponse
	isSet bool
}

func (v NullableProductResponse) Get() *ProductResponse {
	return v.value
}

func (v *NullableProductResponse) Set(val *ProductResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableProductResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableProductResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductResponse(val *ProductResponse) *NullableProductResponse {
	return &NullableProductResponse{value: val, isSet: true}
}

func (v NullableProductResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


