/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the NormalTransactionBody type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NormalTransactionBody{}

// NormalTransactionBody struct for NormalTransactionBody
type NormalTransactionBody struct {
	// The date that this transaction occurred, for accounting purposes.
	AccountingDate *string `json:"accountingDate,omitempty"`
	// The date to use for tax calculations.
	TaxDate *string `json:"taxDate,omitempty"`
	// Three letter ISO currency code (case insensitive).
	CurrencyCode *string `json:"currencyCode,omitempty"`
	Customer *NormalTransactionBodyCustomer `json:"customer,omitempty"`
	Addresses []NormalTransactionBodyAddressesInner `json:"addresses,omitempty"`
	// The input amount in the smallest denomination of the currency (e.g. cents or pennies).
	InputAmount *int64 `json:"inputAmount,omitempty"`
	// The pre-tax amount in the smallest denomination of the currency (e.g. cents or pennies).
	PreTaxAmount *string `json:"preTaxAmount,omitempty"`
	TaxAmountDue *TaxAmountDue `json:"taxAmountDue,omitempty"`
	TaxAmountAdded *NormalTransactionBodyTaxAmountAdded `json:"taxAmountAdded,omitempty"`
	// The expected total amount of the invoice in the smallest denomination of the currency (e.g. cents or pennies).
	InvoiceTotalAmountExpected *int64 `json:"invoiceTotalAmountExpected,omitempty"`
	JurisSummaries []JurisSummary `json:"jurisSummaries,omitempty"`
	LineItems []LineItem `json:"lineItems,omitempty"`
}

// NewNormalTransactionBody instantiates a new NormalTransactionBody object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNormalTransactionBody() *NormalTransactionBody {
	this := NormalTransactionBody{}
	return &this
}

// NewNormalTransactionBodyWithDefaults instantiates a new NormalTransactionBody object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNormalTransactionBodyWithDefaults() *NormalTransactionBody {
	this := NormalTransactionBody{}
	return &this
}

// GetAccountingDate returns the AccountingDate field value if set, zero value otherwise.
func (o *NormalTransactionBody) GetAccountingDate() string {
	if o == nil || IsNil(o.AccountingDate) {
		var ret string
		return ret
	}
	return *o.AccountingDate
}

// GetAccountingDateOk returns a tuple with the AccountingDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NormalTransactionBody) GetAccountingDateOk() (*string, bool) {
	if o == nil || IsNil(o.AccountingDate) {
		return nil, false
	}
	return o.AccountingDate, true
}

// HasAccountingDate returns a boolean if a field has been set.
func (o *NormalTransactionBody) HasAccountingDate() bool {
	if o != nil && !IsNil(o.AccountingDate) {
		return true
	}

	return false
}

// SetAccountingDate gets a reference to the given string and assigns it to the AccountingDate field.
func (o *NormalTransactionBody) SetAccountingDate(v string) {
	o.AccountingDate = &v
}

// GetTaxDate returns the TaxDate field value if set, zero value otherwise.
func (o *NormalTransactionBody) GetTaxDate() string {
	if o == nil || IsNil(o.TaxDate) {
		var ret string
		return ret
	}
	return *o.TaxDate
}

// GetTaxDateOk returns a tuple with the TaxDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NormalTransactionBody) GetTaxDateOk() (*string, bool) {
	if o == nil || IsNil(o.TaxDate) {
		return nil, false
	}
	return o.TaxDate, true
}

// HasTaxDate returns a boolean if a field has been set.
func (o *NormalTransactionBody) HasTaxDate() bool {
	if o != nil && !IsNil(o.TaxDate) {
		return true
	}

	return false
}

// SetTaxDate gets a reference to the given string and assigns it to the TaxDate field.
func (o *NormalTransactionBody) SetTaxDate(v string) {
	o.TaxDate = &v
}

// GetCurrencyCode returns the CurrencyCode field value if set, zero value otherwise.
func (o *NormalTransactionBody) GetCurrencyCode() string {
	if o == nil || IsNil(o.CurrencyCode) {
		var ret string
		return ret
	}
	return *o.CurrencyCode
}

// GetCurrencyCodeOk returns a tuple with the CurrencyCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NormalTransactionBody) GetCurrencyCodeOk() (*string, bool) {
	if o == nil || IsNil(o.CurrencyCode) {
		return nil, false
	}
	return o.CurrencyCode, true
}

// HasCurrencyCode returns a boolean if a field has been set.
func (o *NormalTransactionBody) HasCurrencyCode() bool {
	if o != nil && !IsNil(o.CurrencyCode) {
		return true
	}

	return false
}

// SetCurrencyCode gets a reference to the given string and assigns it to the CurrencyCode field.
func (o *NormalTransactionBody) SetCurrencyCode(v string) {
	o.CurrencyCode = &v
}

// GetCustomer returns the Customer field value if set, zero value otherwise.
func (o *NormalTransactionBody) GetCustomer() NormalTransactionBodyCustomer {
	if o == nil || IsNil(o.Customer) {
		var ret NormalTransactionBodyCustomer
		return ret
	}
	return *o.Customer
}

// GetCustomerOk returns a tuple with the Customer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NormalTransactionBody) GetCustomerOk() (*NormalTransactionBodyCustomer, bool) {
	if o == nil || IsNil(o.Customer) {
		return nil, false
	}
	return o.Customer, true
}

// HasCustomer returns a boolean if a field has been set.
func (o *NormalTransactionBody) HasCustomer() bool {
	if o != nil && !IsNil(o.Customer) {
		return true
	}

	return false
}

// SetCustomer gets a reference to the given NormalTransactionBodyCustomer and assigns it to the Customer field.
func (o *NormalTransactionBody) SetCustomer(v NormalTransactionBodyCustomer) {
	o.Customer = &v
}

// GetAddresses returns the Addresses field value if set, zero value otherwise.
func (o *NormalTransactionBody) GetAddresses() []NormalTransactionBodyAddressesInner {
	if o == nil || IsNil(o.Addresses) {
		var ret []NormalTransactionBodyAddressesInner
		return ret
	}
	return o.Addresses
}

// GetAddressesOk returns a tuple with the Addresses field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NormalTransactionBody) GetAddressesOk() ([]NormalTransactionBodyAddressesInner, bool) {
	if o == nil || IsNil(o.Addresses) {
		return nil, false
	}
	return o.Addresses, true
}

// HasAddresses returns a boolean if a field has been set.
func (o *NormalTransactionBody) HasAddresses() bool {
	if o != nil && !IsNil(o.Addresses) {
		return true
	}

	return false
}

// SetAddresses gets a reference to the given []NormalTransactionBodyAddressesInner and assigns it to the Addresses field.
func (o *NormalTransactionBody) SetAddresses(v []NormalTransactionBodyAddressesInner) {
	o.Addresses = v
}

// GetInputAmount returns the InputAmount field value if set, zero value otherwise.
func (o *NormalTransactionBody) GetInputAmount() int64 {
	if o == nil || IsNil(o.InputAmount) {
		var ret int64
		return ret
	}
	return *o.InputAmount
}

// GetInputAmountOk returns a tuple with the InputAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NormalTransactionBody) GetInputAmountOk() (*int64, bool) {
	if o == nil || IsNil(o.InputAmount) {
		return nil, false
	}
	return o.InputAmount, true
}

// HasInputAmount returns a boolean if a field has been set.
func (o *NormalTransactionBody) HasInputAmount() bool {
	if o != nil && !IsNil(o.InputAmount) {
		return true
	}

	return false
}

// SetInputAmount gets a reference to the given int64 and assigns it to the InputAmount field.
func (o *NormalTransactionBody) SetInputAmount(v int64) {
	o.InputAmount = &v
}

// GetPreTaxAmount returns the PreTaxAmount field value if set, zero value otherwise.
func (o *NormalTransactionBody) GetPreTaxAmount() string {
	if o == nil || IsNil(o.PreTaxAmount) {
		var ret string
		return ret
	}
	return *o.PreTaxAmount
}

// GetPreTaxAmountOk returns a tuple with the PreTaxAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NormalTransactionBody) GetPreTaxAmountOk() (*string, bool) {
	if o == nil || IsNil(o.PreTaxAmount) {
		return nil, false
	}
	return o.PreTaxAmount, true
}

// HasPreTaxAmount returns a boolean if a field has been set.
func (o *NormalTransactionBody) HasPreTaxAmount() bool {
	if o != nil && !IsNil(o.PreTaxAmount) {
		return true
	}

	return false
}

// SetPreTaxAmount gets a reference to the given string and assigns it to the PreTaxAmount field.
func (o *NormalTransactionBody) SetPreTaxAmount(v string) {
	o.PreTaxAmount = &v
}

// GetTaxAmountDue returns the TaxAmountDue field value if set, zero value otherwise.
func (o *NormalTransactionBody) GetTaxAmountDue() TaxAmountDue {
	if o == nil || IsNil(o.TaxAmountDue) {
		var ret TaxAmountDue
		return ret
	}
	return *o.TaxAmountDue
}

// GetTaxAmountDueOk returns a tuple with the TaxAmountDue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NormalTransactionBody) GetTaxAmountDueOk() (*TaxAmountDue, bool) {
	if o == nil || IsNil(o.TaxAmountDue) {
		return nil, false
	}
	return o.TaxAmountDue, true
}

// HasTaxAmountDue returns a boolean if a field has been set.
func (o *NormalTransactionBody) HasTaxAmountDue() bool {
	if o != nil && !IsNil(o.TaxAmountDue) {
		return true
	}

	return false
}

// SetTaxAmountDue gets a reference to the given TaxAmountDue and assigns it to the TaxAmountDue field.
func (o *NormalTransactionBody) SetTaxAmountDue(v TaxAmountDue) {
	o.TaxAmountDue = &v
}

// GetTaxAmountAdded returns the TaxAmountAdded field value if set, zero value otherwise.
func (o *NormalTransactionBody) GetTaxAmountAdded() NormalTransactionBodyTaxAmountAdded {
	if o == nil || IsNil(o.TaxAmountAdded) {
		var ret NormalTransactionBodyTaxAmountAdded
		return ret
	}
	return *o.TaxAmountAdded
}

// GetTaxAmountAddedOk returns a tuple with the TaxAmountAdded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NormalTransactionBody) GetTaxAmountAddedOk() (*NormalTransactionBodyTaxAmountAdded, bool) {
	if o == nil || IsNil(o.TaxAmountAdded) {
		return nil, false
	}
	return o.TaxAmountAdded, true
}

// HasTaxAmountAdded returns a boolean if a field has been set.
func (o *NormalTransactionBody) HasTaxAmountAdded() bool {
	if o != nil && !IsNil(o.TaxAmountAdded) {
		return true
	}

	return false
}

// SetTaxAmountAdded gets a reference to the given NormalTransactionBodyTaxAmountAdded and assigns it to the TaxAmountAdded field.
func (o *NormalTransactionBody) SetTaxAmountAdded(v NormalTransactionBodyTaxAmountAdded) {
	o.TaxAmountAdded = &v
}

// GetInvoiceTotalAmountExpected returns the InvoiceTotalAmountExpected field value if set, zero value otherwise.
func (o *NormalTransactionBody) GetInvoiceTotalAmountExpected() int64 {
	if o == nil || IsNil(o.InvoiceTotalAmountExpected) {
		var ret int64
		return ret
	}
	return *o.InvoiceTotalAmountExpected
}

// GetInvoiceTotalAmountExpectedOk returns a tuple with the InvoiceTotalAmountExpected field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NormalTransactionBody) GetInvoiceTotalAmountExpectedOk() (*int64, bool) {
	if o == nil || IsNil(o.InvoiceTotalAmountExpected) {
		return nil, false
	}
	return o.InvoiceTotalAmountExpected, true
}

// HasInvoiceTotalAmountExpected returns a boolean if a field has been set.
func (o *NormalTransactionBody) HasInvoiceTotalAmountExpected() bool {
	if o != nil && !IsNil(o.InvoiceTotalAmountExpected) {
		return true
	}

	return false
}

// SetInvoiceTotalAmountExpected gets a reference to the given int64 and assigns it to the InvoiceTotalAmountExpected field.
func (o *NormalTransactionBody) SetInvoiceTotalAmountExpected(v int64) {
	o.InvoiceTotalAmountExpected = &v
}

// GetJurisSummaries returns the JurisSummaries field value if set, zero value otherwise.
func (o *NormalTransactionBody) GetJurisSummaries() []JurisSummary {
	if o == nil || IsNil(o.JurisSummaries) {
		var ret []JurisSummary
		return ret
	}
	return o.JurisSummaries
}

// GetJurisSummariesOk returns a tuple with the JurisSummaries field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NormalTransactionBody) GetJurisSummariesOk() ([]JurisSummary, bool) {
	if o == nil || IsNil(o.JurisSummaries) {
		return nil, false
	}
	return o.JurisSummaries, true
}

// HasJurisSummaries returns a boolean if a field has been set.
func (o *NormalTransactionBody) HasJurisSummaries() bool {
	if o != nil && !IsNil(o.JurisSummaries) {
		return true
	}

	return false
}

// SetJurisSummaries gets a reference to the given []JurisSummary and assigns it to the JurisSummaries field.
func (o *NormalTransactionBody) SetJurisSummaries(v []JurisSummary) {
	o.JurisSummaries = v
}

// GetLineItems returns the LineItems field value if set, zero value otherwise.
func (o *NormalTransactionBody) GetLineItems() []LineItem {
	if o == nil || IsNil(o.LineItems) {
		var ret []LineItem
		return ret
	}
	return o.LineItems
}

// GetLineItemsOk returns a tuple with the LineItems field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NormalTransactionBody) GetLineItemsOk() ([]LineItem, bool) {
	if o == nil || IsNil(o.LineItems) {
		return nil, false
	}
	return o.LineItems, true
}

// HasLineItems returns a boolean if a field has been set.
func (o *NormalTransactionBody) HasLineItems() bool {
	if o != nil && !IsNil(o.LineItems) {
		return true
	}

	return false
}

// SetLineItems gets a reference to the given []LineItem and assigns it to the LineItems field.
func (o *NormalTransactionBody) SetLineItems(v []LineItem) {
	o.LineItems = v
}

func (o NormalTransactionBody) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NormalTransactionBody) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AccountingDate) {
		toSerialize["accountingDate"] = o.AccountingDate
	}
	if !IsNil(o.TaxDate) {
		toSerialize["taxDate"] = o.TaxDate
	}
	if !IsNil(o.CurrencyCode) {
		toSerialize["currencyCode"] = o.CurrencyCode
	}
	if !IsNil(o.Customer) {
		toSerialize["customer"] = o.Customer
	}
	if !IsNil(o.Addresses) {
		toSerialize["addresses"] = o.Addresses
	}
	if !IsNil(o.InputAmount) {
		toSerialize["inputAmount"] = o.InputAmount
	}
	if !IsNil(o.PreTaxAmount) {
		toSerialize["preTaxAmount"] = o.PreTaxAmount
	}
	if !IsNil(o.TaxAmountDue) {
		toSerialize["taxAmountDue"] = o.TaxAmountDue
	}
	if !IsNil(o.TaxAmountAdded) {
		toSerialize["taxAmountAdded"] = o.TaxAmountAdded
	}
	if !IsNil(o.InvoiceTotalAmountExpected) {
		toSerialize["invoiceTotalAmountExpected"] = o.InvoiceTotalAmountExpected
	}
	if !IsNil(o.JurisSummaries) {
		toSerialize["jurisSummaries"] = o.JurisSummaries
	}
	if !IsNil(o.LineItems) {
		toSerialize["lineItems"] = o.LineItems
	}
	return toSerialize, nil
}

type NullableNormalTransactionBody struct {
	value *NormalTransactionBody
	isSet bool
}

func (v NullableNormalTransactionBody) Get() *NormalTransactionBody {
	return v.value
}

func (v *NullableNormalTransactionBody) Set(val *NormalTransactionBody) {
	v.value = val
	v.isSet = true
}

func (v NullableNormalTransactionBody) IsSet() bool {
	return v.isSet
}

func (v *NullableNormalTransactionBody) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNormalTransactionBody(val *NormalTransactionBody) *NullableNormalTransactionBody {
	return &NullableNormalTransactionBody{value: val, isSet: true}
}

func (v NullableNormalTransactionBody) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNormalTransactionBody) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


