/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the JurisSummaryTaxIdValidationProcessedTaxIdsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JurisSummaryTaxIdValidationProcessedTaxIdsInner{}

// JurisSummaryTaxIdValidationProcessedTaxIdsInner struct for JurisSummaryTaxIdValidationProcessedTaxIdsInner
type JurisSummaryTaxIdValidationProcessedTaxIdsInner struct {
	// The tax ID.
	TaxId *string `json:"taxId,omitempty"`
	// Whether the tax ID is valid.
	IsValid *bool `json:"isValid,omitempty"`
}

// NewJurisSummaryTaxIdValidationProcessedTaxIdsInner instantiates a new JurisSummaryTaxIdValidationProcessedTaxIdsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJurisSummaryTaxIdValidationProcessedTaxIdsInner() *JurisSummaryTaxIdValidationProcessedTaxIdsInner {
	this := JurisSummaryTaxIdValidationProcessedTaxIdsInner{}
	return &this
}

// NewJurisSummaryTaxIdValidationProcessedTaxIdsInnerWithDefaults instantiates a new JurisSummaryTaxIdValidationProcessedTaxIdsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJurisSummaryTaxIdValidationProcessedTaxIdsInnerWithDefaults() *JurisSummaryTaxIdValidationProcessedTaxIdsInner {
	this := JurisSummaryTaxIdValidationProcessedTaxIdsInner{}
	return &this
}

// GetTaxId returns the TaxId field value if set, zero value otherwise.
func (o *JurisSummaryTaxIdValidationProcessedTaxIdsInner) GetTaxId() string {
	if o == nil || IsNil(o.TaxId) {
		var ret string
		return ret
	}
	return *o.TaxId
}

// GetTaxIdOk returns a tuple with the TaxId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JurisSummaryTaxIdValidationProcessedTaxIdsInner) GetTaxIdOk() (*string, bool) {
	if o == nil || IsNil(o.TaxId) {
		return nil, false
	}
	return o.TaxId, true
}

// HasTaxId returns a boolean if a field has been set.
func (o *JurisSummaryTaxIdValidationProcessedTaxIdsInner) HasTaxId() bool {
	if o != nil && !IsNil(o.TaxId) {
		return true
	}

	return false
}

// SetTaxId gets a reference to the given string and assigns it to the TaxId field.
func (o *JurisSummaryTaxIdValidationProcessedTaxIdsInner) SetTaxId(v string) {
	o.TaxId = &v
}

// GetIsValid returns the IsValid field value if set, zero value otherwise.
func (o *JurisSummaryTaxIdValidationProcessedTaxIdsInner) GetIsValid() bool {
	if o == nil || IsNil(o.IsValid) {
		var ret bool
		return ret
	}
	return *o.IsValid
}

// GetIsValidOk returns a tuple with the IsValid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JurisSummaryTaxIdValidationProcessedTaxIdsInner) GetIsValidOk() (*bool, bool) {
	if o == nil || IsNil(o.IsValid) {
		return nil, false
	}
	return o.IsValid, true
}

// HasIsValid returns a boolean if a field has been set.
func (o *JurisSummaryTaxIdValidationProcessedTaxIdsInner) HasIsValid() bool {
	if o != nil && !IsNil(o.IsValid) {
		return true
	}

	return false
}

// SetIsValid gets a reference to the given bool and assigns it to the IsValid field.
func (o *JurisSummaryTaxIdValidationProcessedTaxIdsInner) SetIsValid(v bool) {
	o.IsValid = &v
}

func (o JurisSummaryTaxIdValidationProcessedTaxIdsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JurisSummaryTaxIdValidationProcessedTaxIdsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.TaxId) {
		toSerialize["taxId"] = o.TaxId
	}
	if !IsNil(o.IsValid) {
		toSerialize["isValid"] = o.IsValid
	}
	return toSerialize, nil
}

type NullableJurisSummaryTaxIdValidationProcessedTaxIdsInner struct {
	value *JurisSummaryTaxIdValidationProcessedTaxIdsInner
	isSet bool
}

func (v NullableJurisSummaryTaxIdValidationProcessedTaxIdsInner) Get() *JurisSummaryTaxIdValidationProcessedTaxIdsInner {
	return v.value
}

func (v *NullableJurisSummaryTaxIdValidationProcessedTaxIdsInner) Set(val *JurisSummaryTaxIdValidationProcessedTaxIdsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableJurisSummaryTaxIdValidationProcessedTaxIdsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableJurisSummaryTaxIdValidationProcessedTaxIdsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJurisSummaryTaxIdValidationProcessedTaxIdsInner(val *JurisSummaryTaxIdValidationProcessedTaxIdsInner) *NullableJurisSummaryTaxIdValidationProcessedTaxIdsInner {
	return &NullableJurisSummaryTaxIdValidationProcessedTaxIdsInner{value: val, isSet: true}
}

func (v NullableJurisSummaryTaxIdValidationProcessedTaxIdsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJurisSummaryTaxIdValidationProcessedTaxIdsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


