/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the InlineObject5FilingsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InlineObject5FilingsInner{}

// InlineObject5FilingsInner struct for InlineObject5FilingsInner
type InlineObject5FilingsInner struct {
	// The ID of the jurisdiction.
	JurisId *string `json:"jurisId,omitempty"`
	// The ID of the filing. This is a unique identifier for the filing within the jurisdiction.
	JurisFilingId *string `json:"jurisFilingId,omitempty"`
	// The name of the filing.
	Name *string `json:"name,omitempty"`
	// Whether the filing is automatically updated based on transaction changes. This is determined based on the status of the filing. For example, a transaction may be automatically added to or removed from a filing if the transaction's accounting date changes while the filing is \"open\". However, the filing is not automatically updated if the filing is locked for seller review. The filing may still be updated manually if this field is true.
	IsAutomaticallyUpdatedForTransactionChanges *bool `json:"isAutomaticallyUpdatedForTransactionChanges,omitempty"`
	// Whether the filing has been filed.
	IsFiled *bool `json:"isFiled,omitempty"`
	Period *InlineObject5FilingsInnerPeriod `json:"period,omitempty"`
}

// NewInlineObject5FilingsInner instantiates a new InlineObject5FilingsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject5FilingsInner() *InlineObject5FilingsInner {
	this := InlineObject5FilingsInner{}
	return &this
}

// NewInlineObject5FilingsInnerWithDefaults instantiates a new InlineObject5FilingsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject5FilingsInnerWithDefaults() *InlineObject5FilingsInner {
	this := InlineObject5FilingsInner{}
	return &this
}

// GetJurisId returns the JurisId field value if set, zero value otherwise.
func (o *InlineObject5FilingsInner) GetJurisId() string {
	if o == nil || IsNil(o.JurisId) {
		var ret string
		return ret
	}
	return *o.JurisId
}

// GetJurisIdOk returns a tuple with the JurisId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject5FilingsInner) GetJurisIdOk() (*string, bool) {
	if o == nil || IsNil(o.JurisId) {
		return nil, false
	}
	return o.JurisId, true
}

// HasJurisId returns a boolean if a field has been set.
func (o *InlineObject5FilingsInner) HasJurisId() bool {
	if o != nil && !IsNil(o.JurisId) {
		return true
	}

	return false
}

// SetJurisId gets a reference to the given string and assigns it to the JurisId field.
func (o *InlineObject5FilingsInner) SetJurisId(v string) {
	o.JurisId = &v
}

// GetJurisFilingId returns the JurisFilingId field value if set, zero value otherwise.
func (o *InlineObject5FilingsInner) GetJurisFilingId() string {
	if o == nil || IsNil(o.JurisFilingId) {
		var ret string
		return ret
	}
	return *o.JurisFilingId
}

// GetJurisFilingIdOk returns a tuple with the JurisFilingId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject5FilingsInner) GetJurisFilingIdOk() (*string, bool) {
	if o == nil || IsNil(o.JurisFilingId) {
		return nil, false
	}
	return o.JurisFilingId, true
}

// HasJurisFilingId returns a boolean if a field has been set.
func (o *InlineObject5FilingsInner) HasJurisFilingId() bool {
	if o != nil && !IsNil(o.JurisFilingId) {
		return true
	}

	return false
}

// SetJurisFilingId gets a reference to the given string and assigns it to the JurisFilingId field.
func (o *InlineObject5FilingsInner) SetJurisFilingId(v string) {
	o.JurisFilingId = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *InlineObject5FilingsInner) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject5FilingsInner) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *InlineObject5FilingsInner) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *InlineObject5FilingsInner) SetName(v string) {
	o.Name = &v
}

// GetIsAutomaticallyUpdatedForTransactionChanges returns the IsAutomaticallyUpdatedForTransactionChanges field value if set, zero value otherwise.
func (o *InlineObject5FilingsInner) GetIsAutomaticallyUpdatedForTransactionChanges() bool {
	if o == nil || IsNil(o.IsAutomaticallyUpdatedForTransactionChanges) {
		var ret bool
		return ret
	}
	return *o.IsAutomaticallyUpdatedForTransactionChanges
}

// GetIsAutomaticallyUpdatedForTransactionChangesOk returns a tuple with the IsAutomaticallyUpdatedForTransactionChanges field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject5FilingsInner) GetIsAutomaticallyUpdatedForTransactionChangesOk() (*bool, bool) {
	if o == nil || IsNil(o.IsAutomaticallyUpdatedForTransactionChanges) {
		return nil, false
	}
	return o.IsAutomaticallyUpdatedForTransactionChanges, true
}

// HasIsAutomaticallyUpdatedForTransactionChanges returns a boolean if a field has been set.
func (o *InlineObject5FilingsInner) HasIsAutomaticallyUpdatedForTransactionChanges() bool {
	if o != nil && !IsNil(o.IsAutomaticallyUpdatedForTransactionChanges) {
		return true
	}

	return false
}

// SetIsAutomaticallyUpdatedForTransactionChanges gets a reference to the given bool and assigns it to the IsAutomaticallyUpdatedForTransactionChanges field.
func (o *InlineObject5FilingsInner) SetIsAutomaticallyUpdatedForTransactionChanges(v bool) {
	o.IsAutomaticallyUpdatedForTransactionChanges = &v
}

// GetIsFiled returns the IsFiled field value if set, zero value otherwise.
func (o *InlineObject5FilingsInner) GetIsFiled() bool {
	if o == nil || IsNil(o.IsFiled) {
		var ret bool
		return ret
	}
	return *o.IsFiled
}

// GetIsFiledOk returns a tuple with the IsFiled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject5FilingsInner) GetIsFiledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsFiled) {
		return nil, false
	}
	return o.IsFiled, true
}

// HasIsFiled returns a boolean if a field has been set.
func (o *InlineObject5FilingsInner) HasIsFiled() bool {
	if o != nil && !IsNil(o.IsFiled) {
		return true
	}

	return false
}

// SetIsFiled gets a reference to the given bool and assigns it to the IsFiled field.
func (o *InlineObject5FilingsInner) SetIsFiled(v bool) {
	o.IsFiled = &v
}

// GetPeriod returns the Period field value if set, zero value otherwise.
func (o *InlineObject5FilingsInner) GetPeriod() InlineObject5FilingsInnerPeriod {
	if o == nil || IsNil(o.Period) {
		var ret InlineObject5FilingsInnerPeriod
		return ret
	}
	return *o.Period
}

// GetPeriodOk returns a tuple with the Period field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject5FilingsInner) GetPeriodOk() (*InlineObject5FilingsInnerPeriod, bool) {
	if o == nil || IsNil(o.Period) {
		return nil, false
	}
	return o.Period, true
}

// HasPeriod returns a boolean if a field has been set.
func (o *InlineObject5FilingsInner) HasPeriod() bool {
	if o != nil && !IsNil(o.Period) {
		return true
	}

	return false
}

// SetPeriod gets a reference to the given InlineObject5FilingsInnerPeriod and assigns it to the Period field.
func (o *InlineObject5FilingsInner) SetPeriod(v InlineObject5FilingsInnerPeriod) {
	o.Period = &v
}

func (o InlineObject5FilingsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InlineObject5FilingsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.JurisId) {
		toSerialize["jurisId"] = o.JurisId
	}
	if !IsNil(o.JurisFilingId) {
		toSerialize["jurisFilingId"] = o.JurisFilingId
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.IsAutomaticallyUpdatedForTransactionChanges) {
		toSerialize["isAutomaticallyUpdatedForTransactionChanges"] = o.IsAutomaticallyUpdatedForTransactionChanges
	}
	if !IsNil(o.IsFiled) {
		toSerialize["isFiled"] = o.IsFiled
	}
	if !IsNil(o.Period) {
		toSerialize["period"] = o.Period
	}
	return toSerialize, nil
}

type NullableInlineObject5FilingsInner struct {
	value *InlineObject5FilingsInner
	isSet bool
}

func (v NullableInlineObject5FilingsInner) Get() *InlineObject5FilingsInner {
	return v.value
}

func (v *NullableInlineObject5FilingsInner) Set(val *InlineObject5FilingsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject5FilingsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject5FilingsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject5FilingsInner(val *InlineObject5FilingsInner) *NullableInlineObject5FilingsInner {
	return &NullableInlineObject5FilingsInner{value: val, isSet: true}
}

func (v NullableInlineObject5FilingsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject5FilingsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


