/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// InlineObject1TransactionsInner - struct for InlineObject1TransactionsInner
type InlineObject1TransactionsInner struct {
	NormalTransactionResponse *NormalTransactionResponse
	VoidedTransactionResponse *VoidedTransactionResponse
}

// NormalTransactionResponseAsInlineObject1TransactionsInner is a convenience function that returns NormalTransactionResponse wrapped in InlineObject1TransactionsInner
func NormalTransactionResponseAsInlineObject1TransactionsInner(v *NormalTransactionResponse) InlineObject1TransactionsInner {
	return InlineObject1TransactionsInner{
		NormalTransactionResponse: v,
	}
}

// VoidedTransactionResponseAsInlineObject1TransactionsInner is a convenience function that returns VoidedTransactionResponse wrapped in InlineObject1TransactionsInner
func VoidedTransactionResponseAsInlineObject1TransactionsInner(v *VoidedTransactionResponse) InlineObject1TransactionsInner {
	return InlineObject1TransactionsInner{
		VoidedTransactionResponse: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *InlineObject1TransactionsInner) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into NormalTransactionResponse
	err = newStrictDecoder(data).Decode(&dst.NormalTransactionResponse)
	if err == nil {
		jsonNormalTransactionResponse, _ := json.Marshal(dst.NormalTransactionResponse)
		if string(jsonNormalTransactionResponse) == "{}" { // empty struct
			dst.NormalTransactionResponse = nil
		} else {
			if err = validator.Validate(dst.NormalTransactionResponse); err != nil {
				dst.NormalTransactionResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.NormalTransactionResponse = nil
	}

	// try to unmarshal data into VoidedTransactionResponse
	err = newStrictDecoder(data).Decode(&dst.VoidedTransactionResponse)
	if err == nil {
		jsonVoidedTransactionResponse, _ := json.Marshal(dst.VoidedTransactionResponse)
		if string(jsonVoidedTransactionResponse) == "{}" { // empty struct
			dst.VoidedTransactionResponse = nil
		} else {
			if err = validator.Validate(dst.VoidedTransactionResponse); err != nil {
				dst.VoidedTransactionResponse = nil
			} else {
				match++
			}
		}
	} else {
		dst.VoidedTransactionResponse = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.NormalTransactionResponse = nil
		dst.VoidedTransactionResponse = nil

		return fmt.Errorf("data matches more than one schema in oneOf(InlineObject1TransactionsInner)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(InlineObject1TransactionsInner)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src InlineObject1TransactionsInner) MarshalJSON() ([]byte, error) {
	if src.NormalTransactionResponse != nil {
		return json.Marshal(&src.NormalTransactionResponse)
	}

	if src.VoidedTransactionResponse != nil {
		return json.Marshal(&src.VoidedTransactionResponse)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *InlineObject1TransactionsInner) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.NormalTransactionResponse != nil {
		return obj.NormalTransactionResponse
	}

	if obj.VoidedTransactionResponse != nil {
		return obj.VoidedTransactionResponse
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj InlineObject1TransactionsInner) GetActualInstanceValue() (interface{}) {
	if obj.NormalTransactionResponse != nil {
		return *obj.NormalTransactionResponse
	}

	if obj.VoidedTransactionResponse != nil {
		return *obj.VoidedTransactionResponse
	}

	// all schemas are nil
	return nil
}

type NullableInlineObject1TransactionsInner struct {
	value *InlineObject1TransactionsInner
	isSet bool
}

func (v NullableInlineObject1TransactionsInner) Get() *InlineObject1TransactionsInner {
	return v.value
}

func (v *NullableInlineObject1TransactionsInner) Set(val *InlineObject1TransactionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject1TransactionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject1TransactionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject1TransactionsInner(val *InlineObject1TransactionsInner) *NullableInlineObject1TransactionsInner {
	return &NullableInlineObject1TransactionsInner{value: val, isSet: true}
}

func (v NullableInlineObject1TransactionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject1TransactionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


