/*
Anrok API

# API reference  The Anrok API server is accessible at “https://api.anrok.com”.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header “Authorization: Bearer {sellerId}/{apiKeyId}/secret.{apiKeySecret}”.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.0.0
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateTransactionCannotComputeTaxAmount type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateTransactionCannotComputeTaxAmount{}

// CreateTransactionCannotComputeTaxAmount Error computing tax amount to be collected
type CreateTransactionCannotComputeTaxAmount struct {
	Type *string `json:"type,omitempty"`
}

// NewCreateTransactionCannotComputeTaxAmount instantiates a new CreateTransactionCannotComputeTaxAmount object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateTransactionCannotComputeTaxAmount() *CreateTransactionCannotComputeTaxAmount {
	this := CreateTransactionCannotComputeTaxAmount{}
	return &this
}

// NewCreateTransactionCannotComputeTaxAmountWithDefaults instantiates a new CreateTransactionCannotComputeTaxAmount object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateTransactionCannotComputeTaxAmountWithDefaults() *CreateTransactionCannotComputeTaxAmount {
	this := CreateTransactionCannotComputeTaxAmount{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *CreateTransactionCannotComputeTaxAmount) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateTransactionCannotComputeTaxAmount) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *CreateTransactionCannotComputeTaxAmount) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *CreateTransactionCannotComputeTaxAmount) SetType(v string) {
	o.Type = &v
}

func (o CreateTransactionCannotComputeTaxAmount) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateTransactionCannotComputeTaxAmount) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableCreateTransactionCannotComputeTaxAmount struct {
	value *CreateTransactionCannotComputeTaxAmount
	isSet bool
}

func (v NullableCreateTransactionCannotComputeTaxAmount) Get() *CreateTransactionCannotComputeTaxAmount {
	return v.value
}

func (v *NullableCreateTransactionCannotComputeTaxAmount) Set(val *CreateTransactionCannotComputeTaxAmount) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateTransactionCannotComputeTaxAmount) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateTransactionCannotComputeTaxAmount) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateTransactionCannotComputeTaxAmount(val *CreateTransactionCannotComputeTaxAmount) *NullableCreateTransactionCannotComputeTaxAmount {
	return &NullableCreateTransactionCannotComputeTaxAmount{value: val, isSet: true}
}

func (v NullableCreateTransactionCannotComputeTaxAmount) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateTransactionCannotComputeTaxAmount) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


