/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ProductsListRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductsListRequest{}

// ProductsListRequest struct for ProductsListRequest
type ProductsListRequest struct {
	// The maximum number of products to return.
	Limit *int32 `json:"limit,omitempty"`
	// The cursor to use for pagination. This is the value of the `nextCursor` field returned from the previous page.
	Cursor *string `json:"cursor,omitempty"`
	// Whether to include default products and default shipping products from any integrations in the response. When `false`, only regular products are returned.
	IncludeDefaultProducts *bool `json:"includeDefaultProducts,omitempty"`
}

// NewProductsListRequest instantiates a new ProductsListRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductsListRequest() *ProductsListRequest {
	this := ProductsListRequest{}
	var limit int32 = 100
	this.Limit = &limit
	var includeDefaultProducts bool = false
	this.IncludeDefaultProducts = &includeDefaultProducts
	return &this
}

// NewProductsListRequestWithDefaults instantiates a new ProductsListRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductsListRequestWithDefaults() *ProductsListRequest {
	this := ProductsListRequest{}
	var limit int32 = 100
	this.Limit = &limit
	var includeDefaultProducts bool = false
	this.IncludeDefaultProducts = &includeDefaultProducts
	return &this
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *ProductsListRequest) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductsListRequest) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *ProductsListRequest) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *ProductsListRequest) SetLimit(v int32) {
	o.Limit = &v
}

// GetCursor returns the Cursor field value if set, zero value otherwise.
func (o *ProductsListRequest) GetCursor() string {
	if o == nil || IsNil(o.Cursor) {
		var ret string
		return ret
	}
	return *o.Cursor
}

// GetCursorOk returns a tuple with the Cursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductsListRequest) GetCursorOk() (*string, bool) {
	if o == nil || IsNil(o.Cursor) {
		return nil, false
	}
	return o.Cursor, true
}

// HasCursor returns a boolean if a field has been set.
func (o *ProductsListRequest) HasCursor() bool {
	if o != nil && !IsNil(o.Cursor) {
		return true
	}

	return false
}

// SetCursor gets a reference to the given string and assigns it to the Cursor field.
func (o *ProductsListRequest) SetCursor(v string) {
	o.Cursor = &v
}

// GetIncludeDefaultProducts returns the IncludeDefaultProducts field value if set, zero value otherwise.
func (o *ProductsListRequest) GetIncludeDefaultProducts() bool {
	if o == nil || IsNil(o.IncludeDefaultProducts) {
		var ret bool
		return ret
	}
	return *o.IncludeDefaultProducts
}

// GetIncludeDefaultProductsOk returns a tuple with the IncludeDefaultProducts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ProductsListRequest) GetIncludeDefaultProductsOk() (*bool, bool) {
	if o == nil || IsNil(o.IncludeDefaultProducts) {
		return nil, false
	}
	return o.IncludeDefaultProducts, true
}

// HasIncludeDefaultProducts returns a boolean if a field has been set.
func (o *ProductsListRequest) HasIncludeDefaultProducts() bool {
	if o != nil && !IsNil(o.IncludeDefaultProducts) {
		return true
	}

	return false
}

// SetIncludeDefaultProducts gets a reference to the given bool and assigns it to the IncludeDefaultProducts field.
func (o *ProductsListRequest) SetIncludeDefaultProducts(v bool) {
	o.IncludeDefaultProducts = &v
}

func (o ProductsListRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductsListRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	if !IsNil(o.Cursor) {
		toSerialize["cursor"] = o.Cursor
	}
	if !IsNil(o.IncludeDefaultProducts) {
		toSerialize["includeDefaultProducts"] = o.IncludeDefaultProducts
	}
	return toSerialize, nil
}

type NullableProductsListRequest struct {
	value *ProductsListRequest
	isSet bool
}

func (v NullableProductsListRequest) Get() *ProductsListRequest {
	return v.value
}

func (v *NullableProductsListRequest) Set(val *ProductsListRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableProductsListRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableProductsListRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductsListRequest(val *ProductsListRequest) *NullableProductsListRequest {
	return &NullableProductsListRequest{value: val, isSet: true}
}

func (v NullableProductsListRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductsListRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


