/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the JurisSummary type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &JurisSummary{}

// JurisSummary Summary of the tax amount due and tax ID validation for a jurisdiction.
type JurisSummary struct {
	// The ID of the jurisdiction.
	Id *string `json:"id,omitempty"`
	// The name of the jurisdiction.
	Name *string `json:"name,omitempty"`
	// The pre-tax amount in the smallest denomination of the currency (e.g. cents or pennies).
	PreTaxAmount *string `json:"preTaxAmount,omitempty"`
	TaxAmountDue *TaxAmountDue `json:"taxAmountDue,omitempty"`
	TaxIdValidation *JurisSummaryTaxIdValidation `json:"taxIdValidation,omitempty"`
}

// NewJurisSummary instantiates a new JurisSummary object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewJurisSummary() *JurisSummary {
	this := JurisSummary{}
	return &this
}

// NewJurisSummaryWithDefaults instantiates a new JurisSummary object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewJurisSummaryWithDefaults() *JurisSummary {
	this := JurisSummary{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *JurisSummary) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JurisSummary) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *JurisSummary) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *JurisSummary) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *JurisSummary) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JurisSummary) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *JurisSummary) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *JurisSummary) SetName(v string) {
	o.Name = &v
}

// GetPreTaxAmount returns the PreTaxAmount field value if set, zero value otherwise.
func (o *JurisSummary) GetPreTaxAmount() string {
	if o == nil || IsNil(o.PreTaxAmount) {
		var ret string
		return ret
	}
	return *o.PreTaxAmount
}

// GetPreTaxAmountOk returns a tuple with the PreTaxAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JurisSummary) GetPreTaxAmountOk() (*string, bool) {
	if o == nil || IsNil(o.PreTaxAmount) {
		return nil, false
	}
	return o.PreTaxAmount, true
}

// HasPreTaxAmount returns a boolean if a field has been set.
func (o *JurisSummary) HasPreTaxAmount() bool {
	if o != nil && !IsNil(o.PreTaxAmount) {
		return true
	}

	return false
}

// SetPreTaxAmount gets a reference to the given string and assigns it to the PreTaxAmount field.
func (o *JurisSummary) SetPreTaxAmount(v string) {
	o.PreTaxAmount = &v
}

// GetTaxAmountDue returns the TaxAmountDue field value if set, zero value otherwise.
func (o *JurisSummary) GetTaxAmountDue() TaxAmountDue {
	if o == nil || IsNil(o.TaxAmountDue) {
		var ret TaxAmountDue
		return ret
	}
	return *o.TaxAmountDue
}

// GetTaxAmountDueOk returns a tuple with the TaxAmountDue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JurisSummary) GetTaxAmountDueOk() (*TaxAmountDue, bool) {
	if o == nil || IsNil(o.TaxAmountDue) {
		return nil, false
	}
	return o.TaxAmountDue, true
}

// HasTaxAmountDue returns a boolean if a field has been set.
func (o *JurisSummary) HasTaxAmountDue() bool {
	if o != nil && !IsNil(o.TaxAmountDue) {
		return true
	}

	return false
}

// SetTaxAmountDue gets a reference to the given TaxAmountDue and assigns it to the TaxAmountDue field.
func (o *JurisSummary) SetTaxAmountDue(v TaxAmountDue) {
	o.TaxAmountDue = &v
}

// GetTaxIdValidation returns the TaxIdValidation field value if set, zero value otherwise.
func (o *JurisSummary) GetTaxIdValidation() JurisSummaryTaxIdValidation {
	if o == nil || IsNil(o.TaxIdValidation) {
		var ret JurisSummaryTaxIdValidation
		return ret
	}
	return *o.TaxIdValidation
}

// GetTaxIdValidationOk returns a tuple with the TaxIdValidation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *JurisSummary) GetTaxIdValidationOk() (*JurisSummaryTaxIdValidation, bool) {
	if o == nil || IsNil(o.TaxIdValidation) {
		return nil, false
	}
	return o.TaxIdValidation, true
}

// HasTaxIdValidation returns a boolean if a field has been set.
func (o *JurisSummary) HasTaxIdValidation() bool {
	if o != nil && !IsNil(o.TaxIdValidation) {
		return true
	}

	return false
}

// SetTaxIdValidation gets a reference to the given JurisSummaryTaxIdValidation and assigns it to the TaxIdValidation field.
func (o *JurisSummary) SetTaxIdValidation(v JurisSummaryTaxIdValidation) {
	o.TaxIdValidation = &v
}

func (o JurisSummary) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o JurisSummary) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.PreTaxAmount) {
		toSerialize["preTaxAmount"] = o.PreTaxAmount
	}
	if !IsNil(o.TaxAmountDue) {
		toSerialize["taxAmountDue"] = o.TaxAmountDue
	}
	if !IsNil(o.TaxIdValidation) {
		toSerialize["taxIdValidation"] = o.TaxIdValidation
	}
	return toSerialize, nil
}

type NullableJurisSummary struct {
	value *JurisSummary
	isSet bool
}

func (v NullableJurisSummary) Get() *JurisSummary {
	return v.value
}

func (v *NullableJurisSummary) Set(val *JurisSummary) {
	v.value = val
	v.isSet = true
}

func (v NullableJurisSummary) IsSet() bool {
	return v.isSet
}

func (v *NullableJurisSummary) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableJurisSummary(val *JurisSummary) *NullableJurisSummary {
	return &NullableJurisSummary{value: val, isSet: true}
}

func (v NullableJurisSummary) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableJurisSummary) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


