/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ValidateTaxIdSuccessJurisesInnerValidTaxIdsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ValidateTaxIdSuccessJurisesInnerValidTaxIdsInner{}

// ValidateTaxIdSuccessJurisesInnerValidTaxIdsInner struct for ValidateTaxIdSuccessJurisesInnerValidTaxIdsInner
type ValidateTaxIdSuccessJurisesInnerValidTaxIdsInner struct {
	// The valid tax ID(s) from the request.
	Value *string `json:"value,omitempty"`
}

// NewValidateTaxIdSuccessJurisesInnerValidTaxIdsInner instantiates a new ValidateTaxIdSuccessJurisesInnerValidTaxIdsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewValidateTaxIdSuccessJurisesInnerValidTaxIdsInner() *ValidateTaxIdSuccessJurisesInnerValidTaxIdsInner {
	this := ValidateTaxIdSuccessJurisesInnerValidTaxIdsInner{}
	return &this
}

// NewValidateTaxIdSuccessJurisesInnerValidTaxIdsInnerWithDefaults instantiates a new ValidateTaxIdSuccessJurisesInnerValidTaxIdsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewValidateTaxIdSuccessJurisesInnerValidTaxIdsInnerWithDefaults() *ValidateTaxIdSuccessJurisesInnerValidTaxIdsInner {
	this := ValidateTaxIdSuccessJurisesInnerValidTaxIdsInner{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ValidateTaxIdSuccessJurisesInnerValidTaxIdsInner) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ValidateTaxIdSuccessJurisesInnerValidTaxIdsInner) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ValidateTaxIdSuccessJurisesInnerValidTaxIdsInner) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ValidateTaxIdSuccessJurisesInnerValidTaxIdsInner) SetValue(v string) {
	o.Value = &v
}

func (o ValidateTaxIdSuccessJurisesInnerValidTaxIdsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ValidateTaxIdSuccessJurisesInnerValidTaxIdsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableValidateTaxIdSuccessJurisesInnerValidTaxIdsInner struct {
	value *ValidateTaxIdSuccessJurisesInnerValidTaxIdsInner
	isSet bool
}

func (v NullableValidateTaxIdSuccessJurisesInnerValidTaxIdsInner) Get() *ValidateTaxIdSuccessJurisesInnerValidTaxIdsInner {
	return v.value
}

func (v *NullableValidateTaxIdSuccessJurisesInnerValidTaxIdsInner) Set(val *ValidateTaxIdSuccessJurisesInnerValidTaxIdsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableValidateTaxIdSuccessJurisesInnerValidTaxIdsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableValidateTaxIdSuccessJurisesInnerValidTaxIdsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableValidateTaxIdSuccessJurisesInnerValidTaxIdsInner(val *ValidateTaxIdSuccessJurisesInnerValidTaxIdsInner) *NullableValidateTaxIdSuccessJurisesInnerValidTaxIdsInner {
	return &NullableValidateTaxIdSuccessJurisesInnerValidTaxIdsInner{value: val, isSet: true}
}

func (v NullableValidateTaxIdSuccessJurisesInnerValidTaxIdsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableValidateTaxIdSuccessJurisesInnerValidTaxIdsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


