/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CertificateRequestsCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CertificateRequestsCreateRequest{}

// CertificateRequestsCreateRequest struct for CertificateRequestsCreateRequest
type CertificateRequestsCreateRequest struct {
	// The Anrok customer ID used to link transactions for the same customer and to look up tax exemption certificates for a customer. This is typically the billing system's customer ID with a prefix to disambiguate. - If customerId is provided without customerName, that customer object must   already exist in Anrok. - If both customerId and customerName are provided, the customer object will   be created if it is not already present. - Customer IDs are unique across the entire seller account. 
	CustomerId string `json:"customerId"`
	// The name of the customer. This is used for display purposes only.
	CustomerName *string `json:"customerName,omitempty"`
	// The email address of the customer contact to send the certificate request to.
	EmailAddress string `json:"emailAddress"`
	// Whether to email the certificate request to the recipient. If `false`, the request is created but no email is sent — you can share the resulting `requestLink` directly.
	SendEmail *bool `json:"sendEmail,omitempty"`
}

type _CertificateRequestsCreateRequest CertificateRequestsCreateRequest

// NewCertificateRequestsCreateRequest instantiates a new CertificateRequestsCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertificateRequestsCreateRequest(customerId string, emailAddress string) *CertificateRequestsCreateRequest {
	this := CertificateRequestsCreateRequest{}
	this.CustomerId = customerId
	this.EmailAddress = emailAddress
	var sendEmail bool = true
	this.SendEmail = &sendEmail
	return &this
}

// NewCertificateRequestsCreateRequestWithDefaults instantiates a new CertificateRequestsCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificateRequestsCreateRequestWithDefaults() *CertificateRequestsCreateRequest {
	this := CertificateRequestsCreateRequest{}
	var sendEmail bool = true
	this.SendEmail = &sendEmail
	return &this
}

// GetCustomerId returns the CustomerId field value
func (o *CertificateRequestsCreateRequest) GetCustomerId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value
// and a boolean to check if the value has been set.
func (o *CertificateRequestsCreateRequest) GetCustomerIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CustomerId, true
}

// SetCustomerId sets field value
func (o *CertificateRequestsCreateRequest) SetCustomerId(v string) {
	o.CustomerId = v
}

// GetCustomerName returns the CustomerName field value if set, zero value otherwise.
func (o *CertificateRequestsCreateRequest) GetCustomerName() string {
	if o == nil || IsNil(o.CustomerName) {
		var ret string
		return ret
	}
	return *o.CustomerName
}

// GetCustomerNameOk returns a tuple with the CustomerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateRequestsCreateRequest) GetCustomerNameOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerName) {
		return nil, false
	}
	return o.CustomerName, true
}

// HasCustomerName returns a boolean if a field has been set.
func (o *CertificateRequestsCreateRequest) HasCustomerName() bool {
	if o != nil && !IsNil(o.CustomerName) {
		return true
	}

	return false
}

// SetCustomerName gets a reference to the given string and assigns it to the CustomerName field.
func (o *CertificateRequestsCreateRequest) SetCustomerName(v string) {
	o.CustomerName = &v
}

// GetEmailAddress returns the EmailAddress field value
func (o *CertificateRequestsCreateRequest) GetEmailAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EmailAddress
}

// GetEmailAddressOk returns a tuple with the EmailAddress field value
// and a boolean to check if the value has been set.
func (o *CertificateRequestsCreateRequest) GetEmailAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EmailAddress, true
}

// SetEmailAddress sets field value
func (o *CertificateRequestsCreateRequest) SetEmailAddress(v string) {
	o.EmailAddress = v
}

// GetSendEmail returns the SendEmail field value if set, zero value otherwise.
func (o *CertificateRequestsCreateRequest) GetSendEmail() bool {
	if o == nil || IsNil(o.SendEmail) {
		var ret bool
		return ret
	}
	return *o.SendEmail
}

// GetSendEmailOk returns a tuple with the SendEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificateRequestsCreateRequest) GetSendEmailOk() (*bool, bool) {
	if o == nil || IsNil(o.SendEmail) {
		return nil, false
	}
	return o.SendEmail, true
}

// HasSendEmail returns a boolean if a field has been set.
func (o *CertificateRequestsCreateRequest) HasSendEmail() bool {
	if o != nil && !IsNil(o.SendEmail) {
		return true
	}

	return false
}

// SetSendEmail gets a reference to the given bool and assigns it to the SendEmail field.
func (o *CertificateRequestsCreateRequest) SetSendEmail(v bool) {
	o.SendEmail = &v
}

func (o CertificateRequestsCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CertificateRequestsCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["customerId"] = o.CustomerId
	if !IsNil(o.CustomerName) {
		toSerialize["customerName"] = o.CustomerName
	}
	toSerialize["emailAddress"] = o.EmailAddress
	if !IsNil(o.SendEmail) {
		toSerialize["sendEmail"] = o.SendEmail
	}
	return toSerialize, nil
}

func (o *CertificateRequestsCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"customerId",
		"emailAddress",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCertificateRequestsCreateRequest := _CertificateRequestsCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCertificateRequestsCreateRequest)

	if err != nil {
		return err
	}

	*o = CertificateRequestsCreateRequest(varCertificateRequestsCreateRequest)

	return err
}

type NullableCertificateRequestsCreateRequest struct {
	value *CertificateRequestsCreateRequest
	isSet bool
}

func (v NullableCertificateRequestsCreateRequest) Get() *CertificateRequestsCreateRequest {
	return v.value
}

func (v *NullableCertificateRequestsCreateRequest) Set(val *CertificateRequestsCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificateRequestsCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificateRequestsCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificateRequestsCreateRequest(val *CertificateRequestsCreateRequest) *NullableCertificateRequestsCreateRequest {
	return &NullableCertificateRequestsCreateRequest{value: val, isSet: true}
}

func (v NullableCertificateRequestsCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificateRequestsCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


