/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the NormalTransactionBodyAddressesInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NormalTransactionBodyAddressesInner{}

// NormalTransactionBodyAddressesInner struct for NormalTransactionBodyAddressesInner
type NormalTransactionBodyAddressesInner struct {
	Address *CustomerAddress `json:"address,omitempty"`
}

// NewNormalTransactionBodyAddressesInner instantiates a new NormalTransactionBodyAddressesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNormalTransactionBodyAddressesInner() *NormalTransactionBodyAddressesInner {
	this := NormalTransactionBodyAddressesInner{}
	return &this
}

// NewNormalTransactionBodyAddressesInnerWithDefaults instantiates a new NormalTransactionBodyAddressesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNormalTransactionBodyAddressesInnerWithDefaults() *NormalTransactionBodyAddressesInner {
	this := NormalTransactionBodyAddressesInner{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *NormalTransactionBodyAddressesInner) GetAddress() CustomerAddress {
	if o == nil || IsNil(o.Address) {
		var ret CustomerAddress
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NormalTransactionBodyAddressesInner) GetAddressOk() (*CustomerAddress, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *NormalTransactionBodyAddressesInner) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given CustomerAddress and assigns it to the Address field.
func (o *NormalTransactionBodyAddressesInner) SetAddress(v CustomerAddress) {
	o.Address = &v
}

func (o NormalTransactionBodyAddressesInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NormalTransactionBodyAddressesInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	return toSerialize, nil
}

type NullableNormalTransactionBodyAddressesInner struct {
	value *NormalTransactionBodyAddressesInner
	isSet bool
}

func (v NullableNormalTransactionBodyAddressesInner) Get() *NormalTransactionBodyAddressesInner {
	return v.value
}

func (v *NullableNormalTransactionBodyAddressesInner) Set(val *NormalTransactionBodyAddressesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableNormalTransactionBodyAddressesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableNormalTransactionBodyAddressesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNormalTransactionBodyAddressesInner(val *NormalTransactionBodyAddressesInner) *NullableNormalTransactionBodyAddressesInner {
	return &NullableNormalTransactionBodyAddressesInner{value: val, isSet: true}
}

func (v NullableNormalTransactionBodyAddressesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNormalTransactionBodyAddressesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


