/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ProductTaxCategoriesList200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ProductTaxCategoriesList200Response{}

// ProductTaxCategoriesList200Response struct for ProductTaxCategoriesList200Response
type ProductTaxCategoriesList200Response struct {
	// The list of all available product tax categories.
	ProductTaxCategories []ProductTaxCategoriesList200ResponseProductTaxCategoriesInner `json:"productTaxCategories"`
}

type _ProductTaxCategoriesList200Response ProductTaxCategoriesList200Response

// NewProductTaxCategoriesList200Response instantiates a new ProductTaxCategoriesList200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewProductTaxCategoriesList200Response(productTaxCategories []ProductTaxCategoriesList200ResponseProductTaxCategoriesInner) *ProductTaxCategoriesList200Response {
	this := ProductTaxCategoriesList200Response{}
	this.ProductTaxCategories = productTaxCategories
	return &this
}

// NewProductTaxCategoriesList200ResponseWithDefaults instantiates a new ProductTaxCategoriesList200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewProductTaxCategoriesList200ResponseWithDefaults() *ProductTaxCategoriesList200Response {
	this := ProductTaxCategoriesList200Response{}
	return &this
}

// GetProductTaxCategories returns the ProductTaxCategories field value
func (o *ProductTaxCategoriesList200Response) GetProductTaxCategories() []ProductTaxCategoriesList200ResponseProductTaxCategoriesInner {
	if o == nil {
		var ret []ProductTaxCategoriesList200ResponseProductTaxCategoriesInner
		return ret
	}

	return o.ProductTaxCategories
}

// GetProductTaxCategoriesOk returns a tuple with the ProductTaxCategories field value
// and a boolean to check if the value has been set.
func (o *ProductTaxCategoriesList200Response) GetProductTaxCategoriesOk() ([]ProductTaxCategoriesList200ResponseProductTaxCategoriesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.ProductTaxCategories, true
}

// SetProductTaxCategories sets field value
func (o *ProductTaxCategoriesList200Response) SetProductTaxCategories(v []ProductTaxCategoriesList200ResponseProductTaxCategoriesInner) {
	o.ProductTaxCategories = v
}

func (o ProductTaxCategoriesList200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ProductTaxCategoriesList200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["productTaxCategories"] = o.ProductTaxCategories
	return toSerialize, nil
}

func (o *ProductTaxCategoriesList200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"productTaxCategories",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varProductTaxCategoriesList200Response := _ProductTaxCategoriesList200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varProductTaxCategoriesList200Response)

	if err != nil {
		return err
	}

	*o = ProductTaxCategoriesList200Response(varProductTaxCategoriesList200Response)

	return err
}

type NullableProductTaxCategoriesList200Response struct {
	value *ProductTaxCategoriesList200Response
	isSet bool
}

func (v NullableProductTaxCategoriesList200Response) Get() *ProductTaxCategoriesList200Response {
	return v.value
}

func (v *NullableProductTaxCategoriesList200Response) Set(val *ProductTaxCategoriesList200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableProductTaxCategoriesList200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableProductTaxCategoriesList200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableProductTaxCategoriesList200Response(val *ProductTaxCategoriesList200Response) *NullableProductTaxCategoriesList200Response {
	return &NullableProductTaxCategoriesList200Response{value: val, isSet: true}
}

func (v NullableProductTaxCategoriesList200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableProductTaxCategoriesList200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


