/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FilingsRemoveTransactions409Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FilingsRemoveTransactions409Response{}

// FilingsRemoveTransactions409Response struct for FilingsRemoveTransactions409Response
type FilingsRemoveTransactions409Response struct {
	Type string `json:"type"`
}

type _FilingsRemoveTransactions409Response FilingsRemoveTransactions409Response

// NewFilingsRemoveTransactions409Response instantiates a new FilingsRemoveTransactions409Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilingsRemoveTransactions409Response(type_ string) *FilingsRemoveTransactions409Response {
	this := FilingsRemoveTransactions409Response{}
	this.Type = type_
	return &this
}

// NewFilingsRemoveTransactions409ResponseWithDefaults instantiates a new FilingsRemoveTransactions409Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilingsRemoveTransactions409ResponseWithDefaults() *FilingsRemoveTransactions409Response {
	this := FilingsRemoveTransactions409Response{}
	return &this
}

// GetType returns the Type field value
func (o *FilingsRemoveTransactions409Response) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *FilingsRemoveTransactions409Response) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *FilingsRemoveTransactions409Response) SetType(v string) {
	o.Type = v
}

func (o FilingsRemoveTransactions409Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FilingsRemoveTransactions409Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *FilingsRemoveTransactions409Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFilingsRemoveTransactions409Response := _FilingsRemoveTransactions409Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFilingsRemoveTransactions409Response)

	if err != nil {
		return err
	}

	*o = FilingsRemoveTransactions409Response(varFilingsRemoveTransactions409Response)

	return err
}

type NullableFilingsRemoveTransactions409Response struct {
	value *FilingsRemoveTransactions409Response
	isSet bool
}

func (v NullableFilingsRemoveTransactions409Response) Get() *FilingsRemoveTransactions409Response {
	return v.value
}

func (v *NullableFilingsRemoveTransactions409Response) Set(val *FilingsRemoveTransactions409Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFilingsRemoveTransactions409Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFilingsRemoveTransactions409Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilingsRemoveTransactions409Response(val *FilingsRemoveTransactions409Response) *NullableFilingsRemoveTransactions409Response {
	return &NullableFilingsRemoveTransactions409Response{value: val, isSet: true}
}

func (v NullableFilingsRemoveTransactions409Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilingsRemoveTransactions409Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


