/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CertificatesListRequestFilter type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CertificatesListRequestFilter{}

// CertificatesListRequestFilter The filter to apply to the returned certificates. Cannot be provided together with `cursor`.
type CertificatesListRequestFilter struct {
	// Only return certificates belonging to this customer.
	CustomerId *string `json:"customerId,omitempty"`
	// Only return certificates with this status. If omitted, certificates of all statuses are returned. 
	Status *string `json:"status,omitempty"`
}

// NewCertificatesListRequestFilter instantiates a new CertificatesListRequestFilter object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCertificatesListRequestFilter() *CertificatesListRequestFilter {
	this := CertificatesListRequestFilter{}
	return &this
}

// NewCertificatesListRequestFilterWithDefaults instantiates a new CertificatesListRequestFilter object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCertificatesListRequestFilterWithDefaults() *CertificatesListRequestFilter {
	this := CertificatesListRequestFilter{}
	return &this
}

// GetCustomerId returns the CustomerId field value if set, zero value otherwise.
func (o *CertificatesListRequestFilter) GetCustomerId() string {
	if o == nil || IsNil(o.CustomerId) {
		var ret string
		return ret
	}
	return *o.CustomerId
}

// GetCustomerIdOk returns a tuple with the CustomerId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificatesListRequestFilter) GetCustomerIdOk() (*string, bool) {
	if o == nil || IsNil(o.CustomerId) {
		return nil, false
	}
	return o.CustomerId, true
}

// HasCustomerId returns a boolean if a field has been set.
func (o *CertificatesListRequestFilter) HasCustomerId() bool {
	if o != nil && !IsNil(o.CustomerId) {
		return true
	}

	return false
}

// SetCustomerId gets a reference to the given string and assigns it to the CustomerId field.
func (o *CertificatesListRequestFilter) SetCustomerId(v string) {
	o.CustomerId = &v
}

// GetStatus returns the Status field value if set, zero value otherwise.
func (o *CertificatesListRequestFilter) GetStatus() string {
	if o == nil || IsNil(o.Status) {
		var ret string
		return ret
	}
	return *o.Status
}

// GetStatusOk returns a tuple with the Status field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CertificatesListRequestFilter) GetStatusOk() (*string, bool) {
	if o == nil || IsNil(o.Status) {
		return nil, false
	}
	return o.Status, true
}

// HasStatus returns a boolean if a field has been set.
func (o *CertificatesListRequestFilter) HasStatus() bool {
	if o != nil && !IsNil(o.Status) {
		return true
	}

	return false
}

// SetStatus gets a reference to the given string and assigns it to the Status field.
func (o *CertificatesListRequestFilter) SetStatus(v string) {
	o.Status = &v
}

func (o CertificatesListRequestFilter) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CertificatesListRequestFilter) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CustomerId) {
		toSerialize["customerId"] = o.CustomerId
	}
	if !IsNil(o.Status) {
		toSerialize["status"] = o.Status
	}
	return toSerialize, nil
}

type NullableCertificatesListRequestFilter struct {
	value *CertificatesListRequestFilter
	isSet bool
}

func (v NullableCertificatesListRequestFilter) Get() *CertificatesListRequestFilter {
	return v.value
}

func (v *NullableCertificatesListRequestFilter) Set(val *CertificatesListRequestFilter) {
	v.value = val
	v.isSet = true
}

func (v NullableCertificatesListRequestFilter) IsSet() bool {
	return v.isSet
}

func (v *NullableCertificatesListRequestFilter) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCertificatesListRequestFilter(val *CertificatesListRequestFilter) *NullableCertificatesListRequestFilter {
	return &NullableCertificatesListRequestFilter{value: val, isSet: true}
}

func (v NullableCertificatesListRequestFilter) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCertificatesListRequestFilter) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


