/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"time"
)

// checks if the NormalTransactionResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NormalTransactionResponse{}

// NormalTransactionResponse Normal transaction
type NormalTransactionResponse struct {
	// The ID of the transaction.
	Id *string `json:"id,omitempty"`
	// The timestamp when the transaction was created in Anrok.
	AnrokCreatedTime *time.Time `json:"anrokCreatedTime,omitempty"`
	// The timesstamp when the transaction was last modified in Anrok.
	AnrokModifiedTime *time.Time `json:"anrokModifiedTime,omitempty"`
	SourceBillingSystem *CommonTransactionPropertiesSourceBillingSystem `json:"sourceBillingSystem,omitempty"`
	Type *string `json:"type,omitempty"`
	Body *NormalTransactionBody `json:"body,omitempty"`
}

// NewNormalTransactionResponse instantiates a new NormalTransactionResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNormalTransactionResponse() *NormalTransactionResponse {
	this := NormalTransactionResponse{}
	return &this
}

// NewNormalTransactionResponseWithDefaults instantiates a new NormalTransactionResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNormalTransactionResponseWithDefaults() *NormalTransactionResponse {
	this := NormalTransactionResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *NormalTransactionResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NormalTransactionResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *NormalTransactionResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *NormalTransactionResponse) SetId(v string) {
	o.Id = &v
}

// GetAnrokCreatedTime returns the AnrokCreatedTime field value if set, zero value otherwise.
func (o *NormalTransactionResponse) GetAnrokCreatedTime() time.Time {
	if o == nil || IsNil(o.AnrokCreatedTime) {
		var ret time.Time
		return ret
	}
	return *o.AnrokCreatedTime
}

// GetAnrokCreatedTimeOk returns a tuple with the AnrokCreatedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NormalTransactionResponse) GetAnrokCreatedTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.AnrokCreatedTime) {
		return nil, false
	}
	return o.AnrokCreatedTime, true
}

// HasAnrokCreatedTime returns a boolean if a field has been set.
func (o *NormalTransactionResponse) HasAnrokCreatedTime() bool {
	if o != nil && !IsNil(o.AnrokCreatedTime) {
		return true
	}

	return false
}

// SetAnrokCreatedTime gets a reference to the given time.Time and assigns it to the AnrokCreatedTime field.
func (o *NormalTransactionResponse) SetAnrokCreatedTime(v time.Time) {
	o.AnrokCreatedTime = &v
}

// GetAnrokModifiedTime returns the AnrokModifiedTime field value if set, zero value otherwise.
func (o *NormalTransactionResponse) GetAnrokModifiedTime() time.Time {
	if o == nil || IsNil(o.AnrokModifiedTime) {
		var ret time.Time
		return ret
	}
	return *o.AnrokModifiedTime
}

// GetAnrokModifiedTimeOk returns a tuple with the AnrokModifiedTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NormalTransactionResponse) GetAnrokModifiedTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.AnrokModifiedTime) {
		return nil, false
	}
	return o.AnrokModifiedTime, true
}

// HasAnrokModifiedTime returns a boolean if a field has been set.
func (o *NormalTransactionResponse) HasAnrokModifiedTime() bool {
	if o != nil && !IsNil(o.AnrokModifiedTime) {
		return true
	}

	return false
}

// SetAnrokModifiedTime gets a reference to the given time.Time and assigns it to the AnrokModifiedTime field.
func (o *NormalTransactionResponse) SetAnrokModifiedTime(v time.Time) {
	o.AnrokModifiedTime = &v
}

// GetSourceBillingSystem returns the SourceBillingSystem field value if set, zero value otherwise.
func (o *NormalTransactionResponse) GetSourceBillingSystem() CommonTransactionPropertiesSourceBillingSystem {
	if o == nil || IsNil(o.SourceBillingSystem) {
		var ret CommonTransactionPropertiesSourceBillingSystem
		return ret
	}
	return *o.SourceBillingSystem
}

// GetSourceBillingSystemOk returns a tuple with the SourceBillingSystem field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NormalTransactionResponse) GetSourceBillingSystemOk() (*CommonTransactionPropertiesSourceBillingSystem, bool) {
	if o == nil || IsNil(o.SourceBillingSystem) {
		return nil, false
	}
	return o.SourceBillingSystem, true
}

// HasSourceBillingSystem returns a boolean if a field has been set.
func (o *NormalTransactionResponse) HasSourceBillingSystem() bool {
	if o != nil && !IsNil(o.SourceBillingSystem) {
		return true
	}

	return false
}

// SetSourceBillingSystem gets a reference to the given CommonTransactionPropertiesSourceBillingSystem and assigns it to the SourceBillingSystem field.
func (o *NormalTransactionResponse) SetSourceBillingSystem(v CommonTransactionPropertiesSourceBillingSystem) {
	o.SourceBillingSystem = &v
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *NormalTransactionResponse) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NormalTransactionResponse) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *NormalTransactionResponse) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *NormalTransactionResponse) SetType(v string) {
	o.Type = &v
}

// GetBody returns the Body field value if set, zero value otherwise.
func (o *NormalTransactionResponse) GetBody() NormalTransactionBody {
	if o == nil || IsNil(o.Body) {
		var ret NormalTransactionBody
		return ret
	}
	return *o.Body
}

// GetBodyOk returns a tuple with the Body field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NormalTransactionResponse) GetBodyOk() (*NormalTransactionBody, bool) {
	if o == nil || IsNil(o.Body) {
		return nil, false
	}
	return o.Body, true
}

// HasBody returns a boolean if a field has been set.
func (o *NormalTransactionResponse) HasBody() bool {
	if o != nil && !IsNil(o.Body) {
		return true
	}

	return false
}

// SetBody gets a reference to the given NormalTransactionBody and assigns it to the Body field.
func (o *NormalTransactionResponse) SetBody(v NormalTransactionBody) {
	o.Body = &v
}

func (o NormalTransactionResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NormalTransactionResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.AnrokCreatedTime) {
		toSerialize["anrokCreatedTime"] = o.AnrokCreatedTime
	}
	if !IsNil(o.AnrokModifiedTime) {
		toSerialize["anrokModifiedTime"] = o.AnrokModifiedTime
	}
	if !IsNil(o.SourceBillingSystem) {
		toSerialize["sourceBillingSystem"] = o.SourceBillingSystem
	}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Body) {
		toSerialize["body"] = o.Body
	}
	return toSerialize, nil
}

type NullableNormalTransactionResponse struct {
	value *NormalTransactionResponse
	isSet bool
}

func (v NullableNormalTransactionResponse) Get() *NormalTransactionResponse {
	return v.value
}

func (v *NullableNormalTransactionResponse) Set(val *NormalTransactionResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNormalTransactionResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNormalTransactionResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNormalTransactionResponse(val *NormalTransactionResponse) *NullableNormalTransactionResponse {
	return &NullableNormalTransactionResponse{value: val, isSet: true}
}

func (v NullableNormalTransactionResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNormalTransactionResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


