/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the InlineObject5 type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InlineObject5{}

// InlineObject5 struct for InlineObject5
type InlineObject5 struct {
	// The list of filings.
	Filings []InlineObject5FilingsInner `json:"filings,omitempty"`
	// The cursor to use for pagination.
	NextCursor *string `json:"nextCursor,omitempty"`
	// Whether there are more filings to fetch.
	HasMore *bool `json:"hasMore,omitempty"`
}

// NewInlineObject5 instantiates a new InlineObject5 object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInlineObject5() *InlineObject5 {
	this := InlineObject5{}
	return &this
}

// NewInlineObject5WithDefaults instantiates a new InlineObject5 object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInlineObject5WithDefaults() *InlineObject5 {
	this := InlineObject5{}
	return &this
}

// GetFilings returns the Filings field value if set, zero value otherwise.
func (o *InlineObject5) GetFilings() []InlineObject5FilingsInner {
	if o == nil || IsNil(o.Filings) {
		var ret []InlineObject5FilingsInner
		return ret
	}
	return o.Filings
}

// GetFilingsOk returns a tuple with the Filings field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject5) GetFilingsOk() ([]InlineObject5FilingsInner, bool) {
	if o == nil || IsNil(o.Filings) {
		return nil, false
	}
	return o.Filings, true
}

// HasFilings returns a boolean if a field has been set.
func (o *InlineObject5) HasFilings() bool {
	if o != nil && !IsNil(o.Filings) {
		return true
	}

	return false
}

// SetFilings gets a reference to the given []InlineObject5FilingsInner and assigns it to the Filings field.
func (o *InlineObject5) SetFilings(v []InlineObject5FilingsInner) {
	o.Filings = v
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise.
func (o *InlineObject5) GetNextCursor() string {
	if o == nil || IsNil(o.NextCursor) {
		var ret string
		return ret
	}
	return *o.NextCursor
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject5) GetNextCursorOk() (*string, bool) {
	if o == nil || IsNil(o.NextCursor) {
		return nil, false
	}
	return o.NextCursor, true
}

// HasNextCursor returns a boolean if a field has been set.
func (o *InlineObject5) HasNextCursor() bool {
	if o != nil && !IsNil(o.NextCursor) {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given string and assigns it to the NextCursor field.
func (o *InlineObject5) SetNextCursor(v string) {
	o.NextCursor = &v
}

// GetHasMore returns the HasMore field value if set, zero value otherwise.
func (o *InlineObject5) GetHasMore() bool {
	if o == nil || IsNil(o.HasMore) {
		var ret bool
		return ret
	}
	return *o.HasMore
}

// GetHasMoreOk returns a tuple with the HasMore field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *InlineObject5) GetHasMoreOk() (*bool, bool) {
	if o == nil || IsNil(o.HasMore) {
		return nil, false
	}
	return o.HasMore, true
}

// HasHasMore returns a boolean if a field has been set.
func (o *InlineObject5) HasHasMore() bool {
	if o != nil && !IsNil(o.HasMore) {
		return true
	}

	return false
}

// SetHasMore gets a reference to the given bool and assigns it to the HasMore field.
func (o *InlineObject5) SetHasMore(v bool) {
	o.HasMore = &v
}

func (o InlineObject5) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InlineObject5) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Filings) {
		toSerialize["filings"] = o.Filings
	}
	if !IsNil(o.NextCursor) {
		toSerialize["nextCursor"] = o.NextCursor
	}
	if !IsNil(o.HasMore) {
		toSerialize["hasMore"] = o.HasMore
	}
	return toSerialize, nil
}

type NullableInlineObject5 struct {
	value *InlineObject5
	isSet bool
}

func (v NullableInlineObject5) Get() *InlineObject5 {
	return v.value
}

func (v *NullableInlineObject5) Set(val *InlineObject5) {
	v.value = val
	v.isSet = true
}

func (v NullableInlineObject5) IsSet() bool {
	return v.isSet
}

func (v *NullableInlineObject5) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInlineObject5(val *InlineObject5) *NullableInlineObject5 {
	return &NullableInlineObject5{value: val, isSet: true}
}

func (v NullableInlineObject5) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInlineObject5) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


