/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the TaxIdsValidate409Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TaxIdsValidate409Response{}

// TaxIdsValidate409Response struct for TaxIdsValidate409Response
type TaxIdsValidate409Response struct {
	Type *string `json:"type,omitempty"`
}

// NewTaxIdsValidate409Response instantiates a new TaxIdsValidate409Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTaxIdsValidate409Response() *TaxIdsValidate409Response {
	this := TaxIdsValidate409Response{}
	return &this
}

// NewTaxIdsValidate409ResponseWithDefaults instantiates a new TaxIdsValidate409Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTaxIdsValidate409ResponseWithDefaults() *TaxIdsValidate409Response {
	this := TaxIdsValidate409Response{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *TaxIdsValidate409Response) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TaxIdsValidate409Response) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *TaxIdsValidate409Response) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *TaxIdsValidate409Response) SetType(v string) {
	o.Type = &v
}

func (o TaxIdsValidate409Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TaxIdsValidate409Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	return toSerialize, nil
}

type NullableTaxIdsValidate409Response struct {
	value *TaxIdsValidate409Response
	isSet bool
}

func (v NullableTaxIdsValidate409Response) Get() *TaxIdsValidate409Response {
	return v.value
}

func (v *NullableTaxIdsValidate409Response) Set(val *TaxIdsValidate409Response) {
	v.value = val
	v.isSet = true
}

func (v NullableTaxIdsValidate409Response) IsSet() bool {
	return v.isSet
}

func (v *NullableTaxIdsValidate409Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTaxIdsValidate409Response(val *TaxIdsValidate409Response) *NullableTaxIdsValidate409Response {
	return &NullableTaxIdsValidate409Response{value: val, isSet: true}
}

func (v NullableTaxIdsValidate409Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTaxIdsValidate409Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


