/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the FilingsRemoveTransactions200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FilingsRemoveTransactions200Response{}

// FilingsRemoveTransactions200Response struct for FilingsRemoveTransactions200Response
type FilingsRemoveTransactions200Response struct {
	// One entry per requested transaction ID, in request order.
	Transactions []FilingsRemoveTransactions200ResponseTransactionsInner `json:"transactions"`
}

type _FilingsRemoveTransactions200Response FilingsRemoveTransactions200Response

// NewFilingsRemoveTransactions200Response instantiates a new FilingsRemoveTransactions200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFilingsRemoveTransactions200Response(transactions []FilingsRemoveTransactions200ResponseTransactionsInner) *FilingsRemoveTransactions200Response {
	this := FilingsRemoveTransactions200Response{}
	this.Transactions = transactions
	return &this
}

// NewFilingsRemoveTransactions200ResponseWithDefaults instantiates a new FilingsRemoveTransactions200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFilingsRemoveTransactions200ResponseWithDefaults() *FilingsRemoveTransactions200Response {
	this := FilingsRemoveTransactions200Response{}
	return &this
}

// GetTransactions returns the Transactions field value
func (o *FilingsRemoveTransactions200Response) GetTransactions() []FilingsRemoveTransactions200ResponseTransactionsInner {
	if o == nil {
		var ret []FilingsRemoveTransactions200ResponseTransactionsInner
		return ret
	}

	return o.Transactions
}

// GetTransactionsOk returns a tuple with the Transactions field value
// and a boolean to check if the value has been set.
func (o *FilingsRemoveTransactions200Response) GetTransactionsOk() ([]FilingsRemoveTransactions200ResponseTransactionsInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Transactions, true
}

// SetTransactions sets field value
func (o *FilingsRemoveTransactions200Response) SetTransactions(v []FilingsRemoveTransactions200ResponseTransactionsInner) {
	o.Transactions = v
}

func (o FilingsRemoveTransactions200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FilingsRemoveTransactions200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["transactions"] = o.Transactions
	return toSerialize, nil
}

func (o *FilingsRemoveTransactions200Response) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"transactions",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varFilingsRemoveTransactions200Response := _FilingsRemoveTransactions200Response{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varFilingsRemoveTransactions200Response)

	if err != nil {
		return err
	}

	*o = FilingsRemoveTransactions200Response(varFilingsRemoveTransactions200Response)

	return err
}

type NullableFilingsRemoveTransactions200Response struct {
	value *FilingsRemoveTransactions200Response
	isSet bool
}

func (v NullableFilingsRemoveTransactions200Response) Get() *FilingsRemoveTransactions200Response {
	return v.value
}

func (v *NullableFilingsRemoveTransactions200Response) Set(val *FilingsRemoveTransactions200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableFilingsRemoveTransactions200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableFilingsRemoveTransactions200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFilingsRemoveTransactions200Response(val *FilingsRemoveTransactions200Response) *NullableFilingsRemoveTransactions200Response {
	return &NullableFilingsRemoveTransactions200Response{value: val, isSet: true}
}

func (v NullableFilingsRemoveTransactions200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFilingsRemoveTransactions200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


