/*
Anrok API

# API reference  The Anrok API server is accessible at `https://api.anrok.com`.  All requests are HTTP POSTs with JSON in the body.  Authentication is via an HTTP header `Authorization: Bearer {apiKey}`.  The default rate limit for a seller account is 10 API requests per second. 

API version: 1.1
Contact: support@anrok.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the LineItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &LineItem{}

// LineItem Line item details
type LineItem struct {
	// The ID of the line item in the source billing system, if available.
	Id NullableString `json:"id,omitempty"`
	Product *LineItemProduct `json:"product,omitempty"`
	// The quantity of the line item.
	Quantity NullableString `json:"quantity,omitempty"`
	// The unit price of the line item in the smallest denomination of the currency (e.g. cents or pennies).
	UnitPrice NullableString `json:"unitPrice,omitempty"`
	// The input amount of the line item in the smallest denomination of the currency (e.g. cents or pennies).
	InputAmount *int64 `json:"inputAmount,omitempty"`
	// The pre-tax amount of the line item in the smallest denomination of the currency (e.g. cents or pennies).
	PreTaxAmount *string `json:"preTaxAmount,omitempty"`
	TaxAmountDue *TaxAmountDue `json:"taxAmountDue,omitempty"`
	Jurises []LineItemJurisesInner `json:"jurises,omitempty"`
}

// NewLineItem instantiates a new LineItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLineItem() *LineItem {
	this := LineItem{}
	return &this
}

// NewLineItemWithDefaults instantiates a new LineItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLineItemWithDefaults() *LineItem {
	this := LineItem{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LineItem) GetId() string {
	if o == nil || IsNil(o.Id.Get()) {
		var ret string
		return ret
	}
	return *o.Id.Get()
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LineItem) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Id.Get(), o.Id.IsSet()
}

// HasId returns a boolean if a field has been set.
func (o *LineItem) HasId() bool {
	if o != nil && o.Id.IsSet() {
		return true
	}

	return false
}

// SetId gets a reference to the given NullableString and assigns it to the Id field.
func (o *LineItem) SetId(v string) {
	o.Id.Set(&v)
}
// SetIdNil sets the value for Id to be an explicit nil
func (o *LineItem) SetIdNil() {
	o.Id.Set(nil)
}

// UnsetId ensures that no value is present for Id, not even an explicit nil
func (o *LineItem) UnsetId() {
	o.Id.Unset()
}

// GetProduct returns the Product field value if set, zero value otherwise.
func (o *LineItem) GetProduct() LineItemProduct {
	if o == nil || IsNil(o.Product) {
		var ret LineItemProduct
		return ret
	}
	return *o.Product
}

// GetProductOk returns a tuple with the Product field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LineItem) GetProductOk() (*LineItemProduct, bool) {
	if o == nil || IsNil(o.Product) {
		return nil, false
	}
	return o.Product, true
}

// HasProduct returns a boolean if a field has been set.
func (o *LineItem) HasProduct() bool {
	if o != nil && !IsNil(o.Product) {
		return true
	}

	return false
}

// SetProduct gets a reference to the given LineItemProduct and assigns it to the Product field.
func (o *LineItem) SetProduct(v LineItemProduct) {
	o.Product = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LineItem) GetQuantity() string {
	if o == nil || IsNil(o.Quantity.Get()) {
		var ret string
		return ret
	}
	return *o.Quantity.Get()
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LineItem) GetQuantityOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Quantity.Get(), o.Quantity.IsSet()
}

// HasQuantity returns a boolean if a field has been set.
func (o *LineItem) HasQuantity() bool {
	if o != nil && o.Quantity.IsSet() {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given NullableString and assigns it to the Quantity field.
func (o *LineItem) SetQuantity(v string) {
	o.Quantity.Set(&v)
}
// SetQuantityNil sets the value for Quantity to be an explicit nil
func (o *LineItem) SetQuantityNil() {
	o.Quantity.Set(nil)
}

// UnsetQuantity ensures that no value is present for Quantity, not even an explicit nil
func (o *LineItem) UnsetQuantity() {
	o.Quantity.Unset()
}

// GetUnitPrice returns the UnitPrice field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *LineItem) GetUnitPrice() string {
	if o == nil || IsNil(o.UnitPrice.Get()) {
		var ret string
		return ret
	}
	return *o.UnitPrice.Get()
}

// GetUnitPriceOk returns a tuple with the UnitPrice field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *LineItem) GetUnitPriceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UnitPrice.Get(), o.UnitPrice.IsSet()
}

// HasUnitPrice returns a boolean if a field has been set.
func (o *LineItem) HasUnitPrice() bool {
	if o != nil && o.UnitPrice.IsSet() {
		return true
	}

	return false
}

// SetUnitPrice gets a reference to the given NullableString and assigns it to the UnitPrice field.
func (o *LineItem) SetUnitPrice(v string) {
	o.UnitPrice.Set(&v)
}
// SetUnitPriceNil sets the value for UnitPrice to be an explicit nil
func (o *LineItem) SetUnitPriceNil() {
	o.UnitPrice.Set(nil)
}

// UnsetUnitPrice ensures that no value is present for UnitPrice, not even an explicit nil
func (o *LineItem) UnsetUnitPrice() {
	o.UnitPrice.Unset()
}

// GetInputAmount returns the InputAmount field value if set, zero value otherwise.
func (o *LineItem) GetInputAmount() int64 {
	if o == nil || IsNil(o.InputAmount) {
		var ret int64
		return ret
	}
	return *o.InputAmount
}

// GetInputAmountOk returns a tuple with the InputAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LineItem) GetInputAmountOk() (*int64, bool) {
	if o == nil || IsNil(o.InputAmount) {
		return nil, false
	}
	return o.InputAmount, true
}

// HasInputAmount returns a boolean if a field has been set.
func (o *LineItem) HasInputAmount() bool {
	if o != nil && !IsNil(o.InputAmount) {
		return true
	}

	return false
}

// SetInputAmount gets a reference to the given int64 and assigns it to the InputAmount field.
func (o *LineItem) SetInputAmount(v int64) {
	o.InputAmount = &v
}

// GetPreTaxAmount returns the PreTaxAmount field value if set, zero value otherwise.
func (o *LineItem) GetPreTaxAmount() string {
	if o == nil || IsNil(o.PreTaxAmount) {
		var ret string
		return ret
	}
	return *o.PreTaxAmount
}

// GetPreTaxAmountOk returns a tuple with the PreTaxAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LineItem) GetPreTaxAmountOk() (*string, bool) {
	if o == nil || IsNil(o.PreTaxAmount) {
		return nil, false
	}
	return o.PreTaxAmount, true
}

// HasPreTaxAmount returns a boolean if a field has been set.
func (o *LineItem) HasPreTaxAmount() bool {
	if o != nil && !IsNil(o.PreTaxAmount) {
		return true
	}

	return false
}

// SetPreTaxAmount gets a reference to the given string and assigns it to the PreTaxAmount field.
func (o *LineItem) SetPreTaxAmount(v string) {
	o.PreTaxAmount = &v
}

// GetTaxAmountDue returns the TaxAmountDue field value if set, zero value otherwise.
func (o *LineItem) GetTaxAmountDue() TaxAmountDue {
	if o == nil || IsNil(o.TaxAmountDue) {
		var ret TaxAmountDue
		return ret
	}
	return *o.TaxAmountDue
}

// GetTaxAmountDueOk returns a tuple with the TaxAmountDue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LineItem) GetTaxAmountDueOk() (*TaxAmountDue, bool) {
	if o == nil || IsNil(o.TaxAmountDue) {
		return nil, false
	}
	return o.TaxAmountDue, true
}

// HasTaxAmountDue returns a boolean if a field has been set.
func (o *LineItem) HasTaxAmountDue() bool {
	if o != nil && !IsNil(o.TaxAmountDue) {
		return true
	}

	return false
}

// SetTaxAmountDue gets a reference to the given TaxAmountDue and assigns it to the TaxAmountDue field.
func (o *LineItem) SetTaxAmountDue(v TaxAmountDue) {
	o.TaxAmountDue = &v
}

// GetJurises returns the Jurises field value if set, zero value otherwise.
func (o *LineItem) GetJurises() []LineItemJurisesInner {
	if o == nil || IsNil(o.Jurises) {
		var ret []LineItemJurisesInner
		return ret
	}
	return o.Jurises
}

// GetJurisesOk returns a tuple with the Jurises field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LineItem) GetJurisesOk() ([]LineItemJurisesInner, bool) {
	if o == nil || IsNil(o.Jurises) {
		return nil, false
	}
	return o.Jurises, true
}

// HasJurises returns a boolean if a field has been set.
func (o *LineItem) HasJurises() bool {
	if o != nil && !IsNil(o.Jurises) {
		return true
	}

	return false
}

// SetJurises gets a reference to the given []LineItemJurisesInner and assigns it to the Jurises field.
func (o *LineItem) SetJurises(v []LineItemJurisesInner) {
	o.Jurises = v
}

func (o LineItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o LineItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if o.Id.IsSet() {
		toSerialize["id"] = o.Id.Get()
	}
	if !IsNil(o.Product) {
		toSerialize["product"] = o.Product
	}
	if o.Quantity.IsSet() {
		toSerialize["quantity"] = o.Quantity.Get()
	}
	if o.UnitPrice.IsSet() {
		toSerialize["unitPrice"] = o.UnitPrice.Get()
	}
	if !IsNil(o.InputAmount) {
		toSerialize["inputAmount"] = o.InputAmount
	}
	if !IsNil(o.PreTaxAmount) {
		toSerialize["preTaxAmount"] = o.PreTaxAmount
	}
	if !IsNil(o.TaxAmountDue) {
		toSerialize["taxAmountDue"] = o.TaxAmountDue
	}
	if !IsNil(o.Jurises) {
		toSerialize["jurises"] = o.Jurises
	}
	return toSerialize, nil
}

type NullableLineItem struct {
	value *LineItem
	isSet bool
}

func (v NullableLineItem) Get() *LineItem {
	return v.value
}

func (v *NullableLineItem) Set(val *LineItem) {
	v.value = val
	v.isSet = true
}

func (v NullableLineItem) IsSet() bool {
	return v.isSet
}

func (v *NullableLineItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLineItem(val *LineItem) *NullableLineItem {
	return &NullableLineItem{value: val, isSet: true}
}

func (v NullableLineItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLineItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


